//! elementwise kernel family — Phase 2. Flat C ABI per contracts/wasm-abi.md §9.
//! Owned by the Phase-2 elementwise agent; other agents do not edit this file.
//!
//! All arithmetic is data-only (no validity pointers) per ABI §8. Null
//! propagation for binary ops is the expression-compiler's responsibility via
//! `validity_and`. SIMD paths are gated by `#[cfg(target_feature = "simd128")]`;
//! both scalar and SIMD builds produce bit-identical results for elementwise ops.
//!
//! Integer arithmetic wraps (two's complement). Integer div/mod by zero writes
//! 0 (or any value) and does NOT trap (ABI §7). Float div/mod follows IEEE-754.
//! Comparison kernels produce Arrow-LSB bitmasks (1 bit/element, §4.2).
//! Padding bits beyond `len` in the final mask byte are always written as 0.

// ========================================================================
// SIMD imports (excluded on non-simd128 targets by cfg)
// ========================================================================
#[cfg(target_feature = "simd128")]
use core::arch::wasm32::v128;

// ========================================================================
// Utility: write `n_bytes` zero bytes starting at `ptr`
// ========================================================================
#[inline(always)]
unsafe fn zero_bytes(ptr: *mut u8, n_bytes: usize) {
    for k in 0..n_bytes {
        *ptr.add(k) = 0;
    }
}

// ========================================================================
// Utility: read one validity bit (returns 0 or 1 as u8)
// vp_ptr == 0 means all-valid; returns 1.
// ========================================================================
#[inline(always)]
unsafe fn vbit(vp_ptr: *const u8, idx: usize) -> u8 {
    if vp_ptr.is_null() {
        1
    } else {
        (*vp_ptr.add(idx >> 3) >> (idx & 7)) & 1
    }
}

// ========================================================================
// MACRO: binary float arithmetic with SIMD (f64x2 or f32x4)
// ========================================================================

macro_rules! float64_bin {
    ($fn_name:ident, $op:tt, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f64,
            b: *const f64,
            out: *mut f64,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 2 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            core::arch::wasm32::v128_load(b.add(i) as *const v128),
                        ),
                    );
                    i += 2;
                }
            }
            while i < n {
                *out.add(i) = *a.add(i) $op *b.add(i);
                i += 1;
            }
        }
    };
}

macro_rules! float32_bin {
    ($fn_name:ident, $op:tt, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f32,
            b: *const f32,
            out: *mut f32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            core::arch::wasm32::v128_load(b.add(i) as *const v128),
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = *a.add(i) $op *b.add(i);
                i += 1;
            }
        }
    };
}

// i32 binary arithmetic (wrapping) with SIMD i32x4
macro_rules! int32_bin {
    ($fn_name:ident, $wrapping:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i32,
            b: *const i32,
            out: *mut i32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            core::arch::wasm32::v128_load(b.add(i) as *const v128),
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(*b.add(i));
                i += 1;
            }
        }
    };
}

// u32 binary arithmetic (wrapping) — same SIMD ops as i32 (bit-identical wrapping)
macro_rules! uint32_bin {
    ($fn_name:ident, $wrapping:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const u32,
            b: *const u32,
            out: *mut u32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            core::arch::wasm32::v128_load(b.add(i) as *const v128),
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(*b.add(i));
                i += 1;
            }
        }
    };
}

// ========================================================================
// MACRO: scalar variants (RHS is a scalar, not a pointer)
// ========================================================================

macro_rules! float64_scalar {
    ($fn_name:ident, $op:tt, $simd_splat:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f64,
            s: f64,
            out: *mut f64,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 2 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            vs,
                        ),
                    );
                    i += 2;
                }
            }
            while i < n {
                *out.add(i) = *a.add(i) $op s;
                i += 1;
            }
        }
    };
}

macro_rules! float32_scalar {
    ($fn_name:ident, $op:tt, $simd_splat:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f32,
            s: f32,
            out: *mut f32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            vs,
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = *a.add(i) $op s;
                i += 1;
            }
        }
    };
}

macro_rules! int32_scalar {
    ($fn_name:ident, $wrapping:ident, $simd_splat:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i32,
            s: i32,
            out: *mut i32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            vs,
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(s);
                i += 1;
            }
        }
    };
}

macro_rules! uint32_scalar {
    ($fn_name:ident, $wrapping:ident, $simd_splat:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const u32,
            s: u32,
            out: *mut u32,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s as i32);
                while i + 4 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            vs,
                        ),
                    );
                    i += 4;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(s);
                i += 1;
            }
        }
    };
}

// ========================================================================
// MACRO: comparison mask (vector vs vector)
// Output: Arrow-LSB bit mask, padding bits = 0.
// ========================================================================

// f64 comparison mask with 8-element SIMD batches (4 × f64x2)
macro_rules! cmp_f64_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f64,
            b: *const f64,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let b0 = core::arch::wasm32::v128_load(b.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 2) as *const v128);
                    let b1 = core::arch::wasm32::v128_load(b.add(i + 2) as *const v128);
                    let a2 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let b2 = core::arch::wasm32::v128_load(b.add(i + 4) as *const v128);
                    let a3 = core::arch::wasm32::v128_load(a.add(i + 6) as *const v128);
                    let b3 = core::arch::wasm32::v128_load(b.add(i + 6) as *const v128);
                    let m0 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a0, b0)) as u8;
                    let m1 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a1, b1)) as u8;
                    let m2 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a2, b2)) as u8;
                    let m3 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a3, b3)) as u8;
                    *out.add(i >> 3) = m0 | (m1 << 2) | (m2 << 4) | (m3 << 6);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op *b.add(i) {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// f32 comparison mask with 8-element SIMD batches (2 × f32x4)
macro_rules! cmp_f32_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f32,
            b: *const f32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let b0 = core::arch::wasm32::v128_load(b.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let b1 = core::arch::wasm32::v128_load(b.add(i + 4) as *const v128);
                    let m0 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a0, b0)) as u8;
                    let m1 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a1, b1)) as u8;
                    *out.add(i >> 3) = (m0 & 0x0f) | ((m1 & 0x0f) << 4);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op *b.add(i) {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// i32 comparison mask (signed) with SIMD.
// In Rust 1.96 / stdarch, signed i32x4 comparisons are named i32x4_gt etc.
// (without _s suffix). The unsigned _u variants are not available directly;
// u32 comparisons are handled by a scalar-only macro below.
macro_rules! cmp_i32s_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i32,
            b: *const i32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let b0 = core::arch::wasm32::v128_load(b.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let b1 = core::arch::wasm32::v128_load(b.add(i + 4) as *const v128);
                    let m0 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a0, b0)) as u8;
                    let m1 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a1, b1)) as u8;
                    *out.add(i >> 3) = (m0 & 0x0f) | ((m1 & 0x0f) << 4);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op *b.add(i) {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// u32 comparison mask (unsigned) — scalar only.
// There is no unsigned i32x4 comparison in Rust 1.96 stdarch without the _u
// suffix functions; the XOR-flip trick would add code size for little gain
// since u32 comparison masks have no JS analog requiring the bench gate.
macro_rules! cmp_u32u_mask {
    ($fn_name:ident, $scalar_op:tt) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const u32,
            b: *const u32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            while i < n {
                if *a.add(i) $scalar_op *b.add(i) {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// ========================================================================
// MACRO: comparison scalar mask (RHS is a scalar)
// ========================================================================

macro_rules! cmp_f64_scalar_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_splat:ident, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f64,
            s: f64,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 2) as *const v128);
                    let a2 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let a3 = core::arch::wasm32::v128_load(a.add(i + 6) as *const v128);
                    let m0 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a0, vs)) as u8;
                    let m1 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a1, vs)) as u8;
                    let m2 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a2, vs)) as u8;
                    let m3 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a3, vs)) as u8;
                    *out.add(i >> 3) = m0 | (m1 << 2) | (m2 << 4) | (m3 << 6);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op s {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

macro_rules! cmp_f32_scalar_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_splat:ident, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const f32,
            s: f32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let m0 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a0, vs)) as u8;
                    let m1 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a1, vs)) as u8;
                    *out.add(i >> 3) = (m0 & 0x0f) | ((m1 & 0x0f) << 4);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op s {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

macro_rules! cmp_i32s_scalar_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_splat:ident, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i32,
            s: i32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i)     as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let m0 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a0, vs)) as u8;
                    let m1 = core::arch::wasm32::i32x4_bitmask(core::arch::wasm32::$simd_cmp(a1, vs)) as u8;
                    *out.add(i >> 3) = (m0 & 0x0f) | ((m1 & 0x0f) << 4);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op s {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// u32 scalar comparison — scalar only (see cmp_u32u_mask! note above).
macro_rules! cmp_u32u_scalar_mask {
    ($fn_name:ident, $scalar_op:tt) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const u32,
            s: u32,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            while i < n {
                if *a.add(i) $scalar_op s {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

// ========================================================================
// § Binary arithmetic vector kernels
// ========================================================================

// f64 arithmetic
float64_bin!(add_f64, +, f64x2_add);
float64_bin!(sub_f64, -, f64x2_sub);
float64_bin!(mul_f64, *, f64x2_mul);
float64_bin!(div_f64, /, f64x2_div);

// f64 mod — no SIMD for fmod; scalar only
#[no_mangle]
pub unsafe extern "C" fn mod_f64(a: *const f64, b: *const f64, out: *mut f64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = *a.add(i) % *b.add(i);
    }
}

// f32 arithmetic
float32_bin!(add_f32, +, f32x4_add);
float32_bin!(sub_f32, -, f32x4_sub);
float32_bin!(mul_f32, *, f32x4_mul);
float32_bin!(div_f32, /, f32x4_div);

#[no_mangle]
pub unsafe extern "C" fn mod_f32(a: *const f32, b: *const f32, out: *mut f32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = *a.add(i) % *b.add(i);
    }
}

// i32 arithmetic (wrapping)
int32_bin!(add_i32, wrapping_add, i32x4_add);
int32_bin!(sub_i32, wrapping_sub, i32x4_sub);
int32_bin!(mul_i32, wrapping_mul, i32x4_mul);

// i32 div/mod — no SIMD integer division in WASM; guard zero divisor.
// checked_div/checked_rem also handle i32::MIN / -1 overflow, returning None.
#[no_mangle]
pub unsafe extern "C" fn div_i32(a: *const i32, b: *const i32, out: *mut i32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_div(*b.add(i)).unwrap_or(0);
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_i32(a: *const i32, b: *const i32, out: *mut i32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_rem(*b.add(i)).unwrap_or(0);
    }
}

// u32 arithmetic (wrapping)
uint32_bin!(add_u32, wrapping_add, i32x4_add);
uint32_bin!(sub_u32, wrapping_sub, i32x4_sub);
uint32_bin!(mul_u32, wrapping_mul, i32x4_mul);

#[no_mangle]
pub unsafe extern "C" fn div_u32(a: *const u32, b: *const u32, out: *mut u32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_div(*b.add(i)).unwrap_or(0);
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_u32(a: *const u32, b: *const u32, out: *mut u32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_rem(*b.add(i)).unwrap_or(0);
    }
}

// ========================================================================
// § Binary arithmetic scalar kernels
// ========================================================================

float64_scalar!(add_f64_scalar, +, f64x2_splat, f64x2_add);
float64_scalar!(sub_f64_scalar, -, f64x2_splat, f64x2_sub);
float64_scalar!(mul_f64_scalar, *, f64x2_splat, f64x2_mul);
float64_scalar!(div_f64_scalar, /, f64x2_splat, f64x2_div);

#[no_mangle]
pub unsafe extern "C" fn mod_f64_scalar(a: *const f64, s: f64, out: *mut f64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = *a.add(i) % s;
    }
}

float32_scalar!(add_f32_scalar, +, f32x4_splat, f32x4_add);
float32_scalar!(sub_f32_scalar, -, f32x4_splat, f32x4_sub);
float32_scalar!(mul_f32_scalar, *, f32x4_splat, f32x4_mul);
float32_scalar!(div_f32_scalar, /, f32x4_splat, f32x4_div);

#[no_mangle]
pub unsafe extern "C" fn mod_f32_scalar(a: *const f32, s: f32, out: *mut f32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = *a.add(i) % s;
    }
}

int32_scalar!(add_i32_scalar, wrapping_add, i32x4_splat, i32x4_add);
int32_scalar!(sub_i32_scalar, wrapping_sub, i32x4_splat, i32x4_sub);
int32_scalar!(mul_i32_scalar, wrapping_mul, i32x4_splat, i32x4_mul);

#[no_mangle]
pub unsafe extern "C" fn div_i32_scalar(a: *const i32, s: i32, out: *mut i32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_div(s).unwrap_or(0);
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_i32_scalar(a: *const i32, s: i32, out: *mut i32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_rem(s).unwrap_or(0);
    }
}

uint32_scalar!(add_u32_scalar, wrapping_add, i32x4_splat, i32x4_add);
uint32_scalar!(sub_u32_scalar, wrapping_sub, i32x4_splat, i32x4_sub);
uint32_scalar!(mul_u32_scalar, wrapping_mul, i32x4_splat, i32x4_mul);

#[no_mangle]
pub unsafe extern "C" fn div_u32_scalar(a: *const u32, s: u32, out: *mut u32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_div(s).unwrap_or(0);
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_u32_scalar(a: *const u32, s: u32, out: *mut u32, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).checked_rem(s).unwrap_or(0);
    }
}

// ========================================================================
// § Unary neg
// ========================================================================

#[no_mangle]
pub unsafe extern "C" fn neg_f64(a: *const f64, out: *mut f64, len: u32) {
    let n = len as usize;
    let mut i = 0usize;
    #[cfg(target_feature = "simd128")]
    {
        while i + 2 <= n {
            core::arch::wasm32::v128_store(
                out.add(i) as *mut v128,
                core::arch::wasm32::f64x2_neg(
                    core::arch::wasm32::v128_load(a.add(i) as *const v128),
                ),
            );
            i += 2;
        }
    }
    while i < n {
        *out.add(i) = -*a.add(i);
        i += 1;
    }
}

#[no_mangle]
pub unsafe extern "C" fn neg_f32(a: *const f32, out: *mut f32, len: u32) {
    let n = len as usize;
    let mut i = 0usize;
    #[cfg(target_feature = "simd128")]
    {
        while i + 4 <= n {
            core::arch::wasm32::v128_store(
                out.add(i) as *mut v128,
                core::arch::wasm32::f32x4_neg(
                    core::arch::wasm32::v128_load(a.add(i) as *const v128),
                ),
            );
            i += 4;
        }
    }
    while i < n {
        *out.add(i) = -*a.add(i);
        i += 1;
    }
}

#[no_mangle]
pub unsafe extern "C" fn neg_i32(a: *const i32, out: *mut i32, len: u32) {
    let n = len as usize;
    let mut i = 0usize;
    #[cfg(target_feature = "simd128")]
    {
        while i + 4 <= n {
            core::arch::wasm32::v128_store(
                out.add(i) as *mut v128,
                core::arch::wasm32::i32x4_neg(
                    core::arch::wasm32::v128_load(a.add(i) as *const v128),
                ),
            );
            i += 4;
        }
    }
    while i < n {
        *out.add(i) = (*a.add(i)).wrapping_neg();
        i += 1;
    }
}

#[no_mangle]
pub unsafe extern "C" fn neg_u32(a: *const u32, out: *mut u32, len: u32) {
    let n = len as usize;
    let mut i = 0usize;
    #[cfg(target_feature = "simd128")]
    {
        while i + 4 <= n {
            core::arch::wasm32::v128_store(
                out.add(i) as *mut v128,
                core::arch::wasm32::i32x4_neg(
                    core::arch::wasm32::v128_load(a.add(i) as *const v128),
                ),
            );
            i += 4;
        }
    }
    while i < n {
        *out.add(i) = (*a.add(i)).wrapping_neg();
        i += 1;
    }
}

// ========================================================================
// § Comparison mask kernels (vector × vector)
// ========================================================================

cmp_f64_mask!(gt_f64_mask, >,  f64x2_gt);
cmp_f64_mask!(ge_f64_mask, >=, f64x2_ge);
cmp_f64_mask!(lt_f64_mask, <,  f64x2_lt);
cmp_f64_mask!(le_f64_mask, <=, f64x2_le);
cmp_f64_mask!(eq_f64_mask, ==, f64x2_eq);
cmp_f64_mask!(ne_f64_mask, !=, f64x2_ne);

cmp_f32_mask!(gt_f32_mask, >,  f32x4_gt);
cmp_f32_mask!(ge_f32_mask, >=, f32x4_ge);
cmp_f32_mask!(lt_f32_mask, <,  f32x4_lt);
cmp_f32_mask!(le_f32_mask, <=, f32x4_le);
cmp_f32_mask!(eq_f32_mask, ==, f32x4_eq);
cmp_f32_mask!(ne_f32_mask, !=, f32x4_ne);

cmp_i32s_mask!(gt_i32_mask, >,  i32x4_gt);
cmp_i32s_mask!(ge_i32_mask, >=, i32x4_ge);
cmp_i32s_mask!(lt_i32_mask, <,  i32x4_lt);
cmp_i32s_mask!(le_i32_mask, <=, i32x4_le);
cmp_i32s_mask!(eq_i32_mask, ==, i32x4_eq);
cmp_i32s_mask!(ne_i32_mask, !=, i32x4_ne);

// u32 comparisons — scalar only (unsigned SIMD ops not exposed in Rust 1.96 stdarch)
cmp_u32u_mask!(gt_u32_mask, >);
cmp_u32u_mask!(ge_u32_mask, >=);
cmp_u32u_mask!(lt_u32_mask, <);
cmp_u32u_mask!(le_u32_mask, <=);
cmp_u32u_mask!(eq_u32_mask, ==);
cmp_u32u_mask!(ne_u32_mask, !=);

// ========================================================================
// § Comparison mask kernels (vector × scalar)
// ========================================================================

cmp_f64_scalar_mask!(gt_f64_scalar_mask, >,  f64x2_splat, f64x2_gt);
cmp_f64_scalar_mask!(ge_f64_scalar_mask, >=, f64x2_splat, f64x2_ge);
cmp_f64_scalar_mask!(lt_f64_scalar_mask, <,  f64x2_splat, f64x2_lt);
cmp_f64_scalar_mask!(le_f64_scalar_mask, <=, f64x2_splat, f64x2_le);
cmp_f64_scalar_mask!(eq_f64_scalar_mask, ==, f64x2_splat, f64x2_eq);
cmp_f64_scalar_mask!(ne_f64_scalar_mask, !=, f64x2_splat, f64x2_ne);

cmp_f32_scalar_mask!(gt_f32_scalar_mask, >,  f32x4_splat, f32x4_gt);
cmp_f32_scalar_mask!(ge_f32_scalar_mask, >=, f32x4_splat, f32x4_ge);
cmp_f32_scalar_mask!(lt_f32_scalar_mask, <,  f32x4_splat, f32x4_lt);
cmp_f32_scalar_mask!(le_f32_scalar_mask, <=, f32x4_splat, f32x4_le);
cmp_f32_scalar_mask!(eq_f32_scalar_mask, ==, f32x4_splat, f32x4_eq);
cmp_f32_scalar_mask!(ne_f32_scalar_mask, !=, f32x4_splat, f32x4_ne);

cmp_i32s_scalar_mask!(gt_i32_scalar_mask, >,  i32x4_splat, i32x4_gt);
cmp_i32s_scalar_mask!(ge_i32_scalar_mask, >=, i32x4_splat, i32x4_ge);
cmp_i32s_scalar_mask!(lt_i32_scalar_mask, <,  i32x4_splat, i32x4_lt);
cmp_i32s_scalar_mask!(le_i32_scalar_mask, <=, i32x4_splat, i32x4_le);
cmp_i32s_scalar_mask!(eq_i32_scalar_mask, ==, i32x4_splat, i32x4_eq);
cmp_i32s_scalar_mask!(ne_i32_scalar_mask, !=, i32x4_splat, i32x4_ne);

// u32 scalar comparisons — scalar only
cmp_u32u_scalar_mask!(gt_u32_scalar_mask, >);
cmp_u32u_scalar_mask!(ge_u32_scalar_mask, >=);
cmp_u32u_scalar_mask!(lt_u32_scalar_mask, <);
cmp_u32u_scalar_mask!(le_u32_scalar_mask, <=);
cmp_u32u_scalar_mask!(eq_u32_scalar_mask, ==);
cmp_u32u_scalar_mask!(ne_u32_scalar_mask, !=);

// ========================================================================
// § Kleene three-valued boolean logic (dtypes.md §4.2)
//
// Bool data is u8 (0 or 1 per element); vp_ptr=0 means all-valid.
//
// AND Kleene: F dominates → F&N=F (valid,0); N&N=N; T&N=N
//   out_valid = (av & bv) | (av & ~ad) | (bv & ~bd)
//   out_data  = ad & bd
//
// OR Kleene: T dominates → T|N=T (valid,1); N|N=N; F|N=N
//   out_valid = (av & bv) | (av & ad) | (bv & bd)
//   out_data  = ad | bd
// ========================================================================

#[no_mangle]
pub unsafe extern "C" fn and_kleene(
    a_ptr: *const u8,
    a_vp:  *const u8,
    b_ptr: *const u8,
    b_vp:  *const u8,
    out_ptr: *mut u8,
    out_vp:  *mut u8,
    len: u32,
) {
    let n = len as usize;
    let nbytes = n.div_ceil(8);
    zero_bytes(out_vp, nbytes);

    for i in 0..n {
        let av = vbit(a_vp, i);
        let bv = vbit(b_vp, i);
        let ad = *a_ptr.add(i) & 1;
        let bd = *b_ptr.add(i) & 1;

        // valid when: both valid, OR a is valid-false, OR b is valid-false
        let out_valid = (av & bv) | (av & (ad ^ 1)) | (bv & (bd ^ 1));
        let out_data  = ad & bd;

        *out_ptr.add(i) = out_data;
        if out_valid != 0 {
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        }
    }
}

#[no_mangle]
pub unsafe extern "C" fn or_kleene(
    a_ptr: *const u8,
    a_vp:  *const u8,
    b_ptr: *const u8,
    b_vp:  *const u8,
    out_ptr: *mut u8,
    out_vp:  *mut u8,
    len: u32,
) {
    let n = len as usize;
    let nbytes = n.div_ceil(8);
    zero_bytes(out_vp, nbytes);

    for i in 0..n {
        let av = vbit(a_vp, i);
        let bv = vbit(b_vp, i);
        let ad = *a_ptr.add(i) & 1;
        let bd = *b_ptr.add(i) & 1;

        // valid when: both valid, OR a is valid-true, OR b is valid-true
        let out_valid = (av & bv) | (av & ad) | (bv & bd);
        let out_data  = ad | bd;

        *out_ptr.add(i) = out_data;
        if out_valid != 0 {
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        }
    }
}

/// NOT bool: ¬T=F, ¬F=T, ¬N=N (validity propagates unchanged).
#[no_mangle]
pub unsafe extern "C" fn not_bool(
    a_ptr: *const u8,
    a_vp:  *const u8,
    out_ptr: *mut u8,
    out_vp:  *mut u8,
    len: u32,
) {
    let n = len as usize;
    let nbytes = n.div_ceil(8);
    zero_bytes(out_vp, nbytes);

    for i in 0..n {
        let av = vbit(a_vp, i);
        let ad = *a_ptr.add(i) & 1;
        *out_ptr.add(i) = ad ^ 1; // flip: 0→1, 1→0
        if av != 0 {
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        }
    }
}

// ========================================================================
// § Validity bitmap ops (byte-level AND/OR; no element-level validity)
// ========================================================================

/// Pointwise AND of two validity bitmaps. `len` is the element count.
/// Both inputs and output are `ceil(len/8)` bytes, Arrow-LSB.
#[no_mangle]
pub unsafe extern "C" fn validity_and(
    a_vp: *const u8,
    b_vp: *const u8,
    out_vp: *mut u8,
    len: u32,
) {
    let nbytes = (len as usize).div_ceil(8);
    for k in 0..nbytes {
        *out_vp.add(k) = *a_vp.add(k) & *b_vp.add(k);
    }
}

/// Pointwise OR of two validity bitmaps.
#[no_mangle]
pub unsafe extern "C" fn validity_or(
    a_vp: *const u8,
    b_vp: *const u8,
    out_vp: *mut u8,
    len: u32,
) {
    let nbytes = (len as usize).div_ceil(8);
    for k in 0..nbytes {
        *out_vp.add(k) = *a_vp.add(k) | *b_vp.add(k);
    }
}

// ========================================================================
// § Cast functions — full matrix from dtypes.md §2
//
// Signature: cast_<from>_<to>(in_ptr, in_vp, out_ptr, out_vp, len)
// in_vp == 0 → all-valid fast path (no null in input).
// out_vp is always written (both null-propagated and range-failure bits).
// ========================================================================

// ---- f64 casts ----

/// f64 → f32: ≈ (round; overflow → ±Inf, not null). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_f64_f32(
    inp: *const f64, in_vp: *const u8,
    out: *mut f32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// f64 → i32: ⚠ trunc toward 0; out-of-range or NaN → null.
#[no_mangle]
pub unsafe extern "C" fn cast_f64_i32(
    inp: *const f64, in_vp: *const u8,
    out: *mut i32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        // In-range: v > -2^31 - 1 (i.e. trunc(v) >= -2^31) AND v < 2^31
        // We use: v > -2147483649.0 && v < 2147483648.0
        // NaN and ±Inf are excluded by the comparisons (NaN compares false).
        if v > -2_147_483_649.0_f64 && v < 2_147_483_648.0_f64 {
            *out.add(i) = v as i32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// f64 → u32: ⚠ trunc toward 0; negative, out-of-range, or NaN → null.
#[no_mangle]
pub unsafe extern "C" fn cast_f64_u32(
    inp: *const f64, in_vp: *const u8,
    out: *mut u32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        // In-range: v >= 0 && v < 2^32 = 4294967296.0
        // NaN and negative values excluded by the first comparison.
        if (0.0_f64..4_294_967_296.0_f64).contains(&v) {
            *out.add(i) = v as u32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// f64 → bool: x≠0→true, 0→false, NaN→null. Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_f64_bool(
    inp: *const f64, in_vp: *const u8,
    out: *mut u8,    out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        if v.is_nan() {
            // NaN → null
            *out.add(i) = 0;
        } else {
            *out.add(i) = if v != 0.0 { 1 } else { 0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        }
    }
}

// ---- f32 casts ----

/// f32 → f64: = (widening, exact). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_f32_f64(
    inp: *const f32, in_vp: *const u8,
    out: *mut f64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// f32 → i32: ⚠ (as f64 → i32). Widen first, then range-check.
#[no_mangle]
pub unsafe extern "C" fn cast_f32_i32(
    inp: *const f32, in_vp: *const u8,
    out: *mut i32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i) as f64;
        if v > -2_147_483_649.0_f64 && v < 2_147_483_648.0_f64 {
            *out.add(i) = v as i32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// f32 → u32: ⚠ (as f64 → u32). Widen first, then range-check.
#[no_mangle]
pub unsafe extern "C" fn cast_f32_u32(
    inp: *const f32, in_vp: *const u8,
    out: *mut u32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i) as f64;
        if (0.0_f64..4_294_967_296.0_f64).contains(&v) {
            *out.add(i) = v as u32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// f32 → bool: ⚠ (as f64 → bool). NaN → null.
#[no_mangle]
pub unsafe extern "C" fn cast_f32_bool(
    inp: *const f32, in_vp: *const u8,
    out: *mut u8,    out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        if v.is_nan() {
            *out.add(i) = 0;
        } else {
            *out.add(i) = if v != 0.0 { 1 } else { 0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        }
    }
}

// ---- i32 casts ----

/// i32 → f64: = (exact). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_i32_f64(
    inp: *const i32, in_vp: *const u8,
    out: *mut f64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// i32 → f32: ≈ (may lose precision for |x| > 2^24). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_i32_f32(
    inp: *const i32, in_vp: *const u8,
    out: *mut f32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// i32 → u32: ⚠ negative → null; non-negative bits are identical.
#[no_mangle]
pub unsafe extern "C" fn cast_i32_u32(
    inp: *const i32, in_vp: *const u8,
    out: *mut u32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        if v >= 0 {
            *out.add(i) = v as u32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// i32 → bool: x≠0→true, 0→false. No range failure. Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_i32_bool(
    inp: *const i32, in_vp: *const u8,
    out: *mut u8,    out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = if *inp.add(i) != 0 { 1 } else { 0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

// ---- u32 casts ----

/// u32 → f64: = (exact). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_u32_f64(
    inp: *const u32, in_vp: *const u8,
    out: *mut f64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// u32 → f32: ≈ (may lose precision for x > 2^24). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_u32_f32(
    inp: *const u32, in_vp: *const u8,
    out: *mut f32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// u32 → i32: ⚠ x > 2^31-1 → null; else bits are identical.
#[no_mangle]
pub unsafe extern "C" fn cast_u32_i32(
    inp: *const u32, in_vp: *const u8,
    out: *mut i32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) == 0 {
            *out.add(i) = 0;
            continue;
        }
        let v = *inp.add(i);
        if v <= i32::MAX as u32 {
            *out.add(i) = v as i32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// u32 → bool: x≠0→true, 0→false. No range failure. Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_u32_bool(
    inp: *const u32, in_vp: *const u8,
    out: *mut u8,    out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = if *inp.add(i) != 0 { 1 } else { 0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

// ---- bool casts ----

/// bool → f64: = (exact, true→1.0, false→0.0). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_bool_f64(
    inp: *const u8, in_vp: *const u8,
    out: *mut f64,  out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = if *inp.add(i) != 0 { 1.0 } else { 0.0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// bool → f32: = (exact). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_bool_f32(
    inp: *const u8, in_vp: *const u8,
    out: *mut f32,  out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = if *inp.add(i) != 0 { 1.0 } else { 0.0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// bool → i32: = (true→1, false→0). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_bool_i32(
    inp: *const u8, in_vp: *const u8,
    out: *mut i32,  out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = (*inp.add(i) & 1) as i32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// bool → u32: = (true→1, false→0). Null propagates.
#[no_mangle]
pub unsafe extern "C" fn cast_bool_u32(
    inp: *const u8, in_vp: *const u8,
    out: *mut u32,  out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = (*inp.add(i) & 1) as u32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

// ========================================================================
// § fill_null_dt: replace null slots with `fill`; output is always all-valid.
//   Signature: (in_ptr, in_vp, fill, out_ptr, len)
//   in_vp == 0 → all-valid (just copy in → out).
//   No out_vp: the result has no nulls.
// ========================================================================

#[no_mangle]
pub unsafe extern "C" fn fill_null_f64(
    inp: *const f64, in_vp: *const u8,
    fill: f64,
    out: *mut f64,
    len: u32,
) {
    let n = len as usize;
    if in_vp.is_null() {
        // All valid: fast copy
        for i in 0..n { *out.add(i) = *inp.add(i); }
        return;
    }
    for i in 0..n {
        *out.add(i) = if vbit(in_vp, i) != 0 { *inp.add(i) } else { fill };
    }
}

#[no_mangle]
pub unsafe extern "C" fn fill_null_f32(
    inp: *const f32, in_vp: *const u8,
    fill: f32,
    out: *mut f32,
    len: u32,
) {
    let n = len as usize;
    if in_vp.is_null() {
        for i in 0..n { *out.add(i) = *inp.add(i); }
        return;
    }
    for i in 0..n {
        *out.add(i) = if vbit(in_vp, i) != 0 { *inp.add(i) } else { fill };
    }
}

#[no_mangle]
pub unsafe extern "C" fn fill_null_i32(
    inp: *const i32, in_vp: *const u8,
    fill: i32,
    out: *mut i32,
    len: u32,
) {
    let n = len as usize;
    if in_vp.is_null() {
        for i in 0..n { *out.add(i) = *inp.add(i); }
        return;
    }
    for i in 0..n {
        *out.add(i) = if vbit(in_vp, i) != 0 { *inp.add(i) } else { fill };
    }
}

#[no_mangle]
pub unsafe extern "C" fn fill_null_u32(
    inp: *const u32, in_vp: *const u8,
    fill: u32,
    out: *mut u32,
    len: u32,
) {
    let n = len as usize;
    if in_vp.is_null() {
        for i in 0..n { *out.add(i) = *inp.add(i); }
        return;
    }
    for i in 0..n {
        *out.add(i) = if vbit(in_vp, i) != 0 { *inp.add(i) } else { fill };
    }
}

// ========================================================================
// § is_null: validity bitmap → u8 bool column (1=null, 0=valid).
//   No output nulls. vp_ptr == 0 → all-valid → output all 0.
// ========================================================================

#[no_mangle]
pub unsafe extern "C" fn is_null(vp: *const u8, out_bool: *mut u8, len: u32) {
    let n = len as usize;
    if vp.is_null() {
        // All valid → all outputs = 0 (not null)
        for i in 0..n { *out_bool.add(i) = 0; }
        return;
    }
    for i in 0..n {
        // is_null = 1 iff the validity bit is 0
        *out_bool.add(i) = vbit(vp, i) ^ 1;
    }
}

// ========================================================================
// § expand_mask_bool: 1-bit Arrow-LSB mask → u8 bool column.
//   Padding bits in the last byte are ignored (only `len` elements written).
// ========================================================================

#[no_mangle]
pub unsafe extern "C" fn expand_mask_bool(mask: *const u8, out_u8: *mut u8, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out_u8.add(i) = (*mask.add(i >> 3) >> (i & 7)) & 1;
    }
}

// ========================================================================
// § i64 kernels (v2.3) — wasm-abi.md §10
//
// SIMD policy (§10.5): i64x2 for add/sub/neg/comparisons only.
// mul/div/mod are scalar in BOTH builds (no i64x2.mul in WASM SIMD128).
// ========================================================================

// ── i64 binary arithmetic ─────────────────────────────────────────────────────

macro_rules! int64_bin {
    ($fn_name:ident, $wrapping:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i64,
            b: *const i64,
            out: *mut i64,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 2 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            core::arch::wasm32::v128_load(b.add(i) as *const v128),
                        ),
                    );
                    i += 2;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(*b.add(i));
                i += 1;
            }
        }
    };
}

int64_bin!(add_i64, wrapping_add, i64x2_add);
int64_bin!(sub_i64, wrapping_sub, i64x2_sub);

// mul/div/mod: scalar only (no i64x2.mul in WASM SIMD128)

#[no_mangle]
pub unsafe extern "C" fn mul_i64(a: *const i64, b: *const i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = (*a.add(i)).wrapping_mul(*b.add(i));
    }
}

// Guard zero divisor; wrapping_div handles MIN/-1 → MIN without panic.
#[no_mangle]
pub unsafe extern "C" fn div_i64(a: *const i64, b: *const i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        let bv = *b.add(i);
        *out.add(i) = if bv == 0 { 0 } else { (*a.add(i)).wrapping_div(bv) };
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_i64(a: *const i64, b: *const i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        let bv = *b.add(i);
        *out.add(i) = if bv == 0 { 0 } else { (*a.add(i)).wrapping_rem(bv) };
    }
}

// ── i64 scalar arithmetic ─────────────────────────────────────────────────────

macro_rules! int64_scalar {
    ($fn_name:ident, $wrapping:ident, $simd_splat:ident, $simd_op:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i64,
            s: i64,
            out: *mut i64,
            len: u32,
        ) {
            let n = len as usize;
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 2 <= n {
                    core::arch::wasm32::v128_store(
                        out.add(i) as *mut v128,
                        core::arch::wasm32::$simd_op(
                            core::arch::wasm32::v128_load(a.add(i) as *const v128),
                            vs,
                        ),
                    );
                    i += 2;
                }
            }
            while i < n {
                *out.add(i) = (*a.add(i)).$wrapping(s);
                i += 1;
            }
        }
    };
}

int64_scalar!(add_i64_scalar, wrapping_add, i64x2_splat, i64x2_add);
int64_scalar!(sub_i64_scalar, wrapping_sub, i64x2_splat, i64x2_sub);

#[no_mangle]
pub unsafe extern "C" fn mul_i64_scalar(a: *const i64, s: i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n { *out.add(i) = (*a.add(i)).wrapping_mul(s); }
}

#[no_mangle]
pub unsafe extern "C" fn div_i64_scalar(a: *const i64, s: i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = if s == 0 { 0 } else { (*a.add(i)).wrapping_div(s) };
    }
}

#[no_mangle]
pub unsafe extern "C" fn mod_i64_scalar(a: *const i64, s: i64, out: *mut i64, len: u32) {
    let n = len as usize;
    for i in 0..n {
        *out.add(i) = if s == 0 { 0 } else { (*a.add(i)).wrapping_rem(s) };
    }
}

// ── neg_i64 ───────────────────────────────────────────────────────────────────

#[no_mangle]
pub unsafe extern "C" fn neg_i64(a: *const i64, out: *mut i64, len: u32) {
    let n = len as usize;
    let mut i = 0usize;
    #[cfg(target_feature = "simd128")]
    {
        while i + 2 <= n {
            core::arch::wasm32::v128_store(
                out.add(i) as *mut v128,
                core::arch::wasm32::i64x2_neg(
                    core::arch::wasm32::v128_load(a.add(i) as *const v128),
                ),
            );
            i += 2;
        }
    }
    while i < n {
        *out.add(i) = (*a.add(i)).wrapping_neg();
        i += 1;
    }
}

// ── i64 comparison masks (signed) — 8-element SIMD batch like f64 ────────────
// i64x2 has 2 lanes; i64x2_bitmask extracts bit[63] of each 64-bit lane.

macro_rules! cmp_i64s_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i64,
            b: *const i64,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i    ) as *const v128);
                    let b0 = core::arch::wasm32::v128_load(b.add(i    ) as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 2) as *const v128);
                    let b1 = core::arch::wasm32::v128_load(b.add(i + 2) as *const v128);
                    let a2 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let b2 = core::arch::wasm32::v128_load(b.add(i + 4) as *const v128);
                    let a3 = core::arch::wasm32::v128_load(a.add(i + 6) as *const v128);
                    let b3 = core::arch::wasm32::v128_load(b.add(i + 6) as *const v128);
                    let m0 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a0, b0)) as u8;
                    let m1 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a1, b1)) as u8;
                    let m2 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a2, b2)) as u8;
                    let m3 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a3, b3)) as u8;
                    *out.add(i >> 3) = m0 | (m1 << 2) | (m2 << 4) | (m3 << 6);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op *b.add(i) {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

cmp_i64s_mask!(gt_i64_mask, >,  i64x2_gt);
cmp_i64s_mask!(ge_i64_mask, >=, i64x2_ge);
cmp_i64s_mask!(lt_i64_mask, <,  i64x2_lt);
cmp_i64s_mask!(le_i64_mask, <=, i64x2_le);
cmp_i64s_mask!(eq_i64_mask, ==, i64x2_eq);
cmp_i64s_mask!(ne_i64_mask, !=, i64x2_ne);

// ── i64 scalar comparison masks ───────────────────────────────────────────────

macro_rules! cmp_i64s_scalar_mask {
    ($fn_name:ident, $scalar_op:tt, $simd_splat:ident, $simd_cmp:ident) => {
        #[no_mangle]
        pub unsafe extern "C" fn $fn_name(
            a: *const i64,
            s: i64,
            out: *mut u8,
            len: u32,
        ) {
            let n = len as usize;
            zero_bytes(out, n.div_ceil(8));
            let mut i = 0usize;
            #[cfg(target_feature = "simd128")]
            {
                let vs = core::arch::wasm32::$simd_splat(s);
                while i + 8 <= n {
                    let a0 = core::arch::wasm32::v128_load(a.add(i    ) as *const v128);
                    let a1 = core::arch::wasm32::v128_load(a.add(i + 2) as *const v128);
                    let a2 = core::arch::wasm32::v128_load(a.add(i + 4) as *const v128);
                    let a3 = core::arch::wasm32::v128_load(a.add(i + 6) as *const v128);
                    let m0 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a0, vs)) as u8;
                    let m1 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a1, vs)) as u8;
                    let m2 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a2, vs)) as u8;
                    let m3 = core::arch::wasm32::i64x2_bitmask(core::arch::wasm32::$simd_cmp(a3, vs)) as u8;
                    *out.add(i >> 3) = m0 | (m1 << 2) | (m2 << 4) | (m3 << 6);
                    i += 8;
                }
            }
            while i < n {
                if *a.add(i) $scalar_op s {
                    *out.add(i >> 3) |= 1u8 << (i & 7);
                }
                i += 1;
            }
        }
    };
}

cmp_i64s_scalar_mask!(gt_i64_scalar_mask, >,  i64x2_splat, i64x2_gt);
cmp_i64s_scalar_mask!(ge_i64_scalar_mask, >=, i64x2_splat, i64x2_ge);
cmp_i64s_scalar_mask!(lt_i64_scalar_mask, <,  i64x2_splat, i64x2_lt);
cmp_i64s_scalar_mask!(le_i64_scalar_mask, <=, i64x2_splat, i64x2_le);
cmp_i64s_scalar_mask!(eq_i64_scalar_mask, ==, i64x2_splat, i64x2_eq);
cmp_i64s_scalar_mask!(ne_i64_scalar_mask, !=, i64x2_splat, i64x2_ne);

// ── i64 cast functions ────────────────────────────────────────────────────────

/// f64 → i64: truncate toward 0. NaN/±Inf/out-of-range → null.
/// prevDouble(2^63) = 9223372036854774784.0 < 2^63 → VALID (dtypes.md §7.1).
#[no_mangle]
pub unsafe extern "C" fn cast_f64_i64(
    inp: *const f64, in_vp: *const u8,
    out: *mut i64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    const LO: f64 = -9_223_372_036_854_775_808.0_f64;
    const HI: f64 =  9_223_372_036_854_775_808.0_f64;
    for i in 0..n {
        if vbit(in_vp, i) == 0 { *out.add(i) = 0; continue; }
        let v = *inp.add(i);
        if (LO..HI).contains(&v) {
            *out.add(i) = v as i64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// f32 → i64: widen to f64 first, same range check.
#[no_mangle]
pub unsafe extern "C" fn cast_f32_i64(
    inp: *const f32, in_vp: *const u8,
    out: *mut i64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    const LO: f64 = -9_223_372_036_854_775_808.0_f64;
    const HI: f64 =  9_223_372_036_854_775_808.0_f64;
    for i in 0..n {
        if vbit(in_vp, i) == 0 { *out.add(i) = 0; continue; }
        let v = *inp.add(i) as f64;
        if (LO..HI).contains(&v) {
            *out.add(i) = v as i64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// i32 → i64: sign-extend. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i32_i64(
    inp: *const i32, in_vp: *const u8,
    out: *mut i64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as i64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// u32 → i64: zero-extend. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_u32_i64(
    inp: *const u32, in_vp: *const u8,
    out: *mut i64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as i64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// bool → i64: true→1, false→0. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_bool_i64(
    inp: *const u8, in_vp: *const u8,
    out: *mut i64,  out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = (*inp.add(i) & 1) as i64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// i64 → f64: nearest-even rounding via Rust `as`. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i64_f64(
    inp: *const i64, in_vp: *const u8,
    out: *mut f64,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f64;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// i64 → f32: nearest-even rounding. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i64_f32(
    inp: *const i64, in_vp: *const u8,
    out: *mut f32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as f32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0.0;
        }
    }
}

/// i64 → i32: wrap-truncate (low 32 bits). Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i64_i32(
    inp: *const i64, in_vp: *const u8,
    out: *mut i32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as i32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// i64 → u32: wrap-truncate (low 32 bits, unsigned view). Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i64_u32(
    inp: *const i64, in_vp: *const u8,
    out: *mut u32,   out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = *inp.add(i) as u32;
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

/// i64 → bool: x≠0 → 1, x=0 → 0. Always valid when input is valid.
#[no_mangle]
pub unsafe extern "C" fn cast_i64_bool(
    inp: *const i64, in_vp: *const u8,
    out: *mut u8,    out_vp: *mut u8,
    len: u32,
) {
    let n = len as usize;
    zero_bytes(out_vp, n.div_ceil(8));
    for i in 0..n {
        if vbit(in_vp, i) != 0 {
            *out.add(i) = if *inp.add(i) != 0 { 1 } else { 0 };
            *out_vp.add(i >> 3) |= 1u8 << (i & 7);
        } else {
            *out.add(i) = 0;
        }
    }
}

// ── fill_null_i64 ─────────────────────────────────────────────────────────────

/// Replace null slots with fill value. in_vp=0 → all-valid fast copy.
#[no_mangle]
pub unsafe extern "C" fn fill_null_i64(
    inp: *const i64, in_vp: *const u8,
    fill: i64,
    out: *mut i64,
    len: u32,
) {
    let n = len as usize;
    if in_vp.is_null() {
        for i in 0..n { *out.add(i) = *inp.add(i); }
        return;
    }
    for i in 0..n {
        *out.add(i) = if vbit(in_vp, i) != 0 { *inp.add(i) } else { fill };
    }
}
