//! Hash / relational kernel family — Phase 2. Flat C ABI per contracts/wasm-abi.md §9.
//! Owned by the Phase-2 hash agent (Agent D); other agents do not edit this file.
//!
//! ## Hash function: splitmix64 finalizer
//!
//! All `hash_dt` kernels produce 64-bit hashes via the **splitmix64** finalizer
//! (Sebastiano Vigna, 2015; also the Murmur3 finalizer family). It is a bijective
//! mapping on u64 with excellent avalanche properties:
//!
//! ```text
//! fn splitmix64(x: u64) -> u64 {
//!     let x = x ^ (x >> 30);
//!     let x = x.wrapping_mul(0xbf58476d1ce4e5b9);
//!     let x = x ^ (x >> 27);
//!     let x = x.wrapping_mul(0x94d049bb133111eb);
//!     x ^ (x >> 31)
//! }
//! ```
//!
//! Seeds per dtype:
//! - `i32`: sign-extend to i64, zero-extend to u64 (`v as i64 as u64`)
//! - `u32`: zero-extend to u64 (`v as u64`)
//! - `f64`: canonicalize (-0.0→+0.0, any-NaN→canonical-NaN), then `to_bits()`
//! - `f32`: canonicalize (-0.0f32→+0.0f32, any-NaN→canonical-NaN),
//!   then `f32::to_bits() as u64` (zero-extended)
//!
//! ## H_NULL = 0x9e3779b97f4a7c15
//!
//! Null rows (validity bit = 0) always hash to the reserved constant `H_NULL`
//! regardless of the data value (ABI §9 D). This value is the 64-bit Fibonacci
//! hash constant and is extremely unlikely to collide with any splitmix64 output
//! in practice (it is not in the range of splitmix64 for any u64 input — verified
//! by the fact that splitmix64 is a bijection and H_NULL would map to 0 which we
//! never feed as a seed; in practice collision probability is negligible).
//!
//! ## Hash table slot layout (16 bytes, zero-initialized by caller)
//!
//! ```text
//! offset  0..8   key_hash: i64   — hash value stored in slot
//! offset  8..12  val: i32        — group_id (group_build) or r_idx (joins)
//! offset 12..16  occupied: i32   — 0 = empty, 1 = occupied
//! ```
//!
//! Open-addressing with linear probing. Probe stop condition: empty slot.
//!
//! ## SIMD
//!
//! `hash_dt` kernels use the same splitmix64 scalar loop in both builds.
//! WASM SIMD128 lacks `i64x2.mul`; a 64-bit multiply is the core of splitmix64
//! and cannot be vectorised with the available instruction set without falling back
//! to an emulated 32×32→64 multiply (complex and unlikely to be faster than the
//! scalar JIT path given memory-bandwidth domination). `group_build` and `join_*`
//! are sequential by nature (each slot write depends on probe outcome); SIMD gives
//! no algorithmic improvement there.
//!
//! `hash_combine` processes acc/add pairs; both SIMD and scalar builds use the
//! same scalar loop — see above reasoning.

// ---------------------------------------------------------------------------
// Canonical NaN value for f64/f32 canonicalization
// ---------------------------------------------------------------------------

const CANONICAL_F64_NAN_BITS: u64 = 0x7FF8_0000_0000_0000;
const CANONICAL_F32_NAN_BITS: u32 = 0x7FC0_0000;

/// Reserved null-row hash (ABI §9 D). All null-validity rows hash to this value.
const H_NULL: i64 = 0x9e37_79b9_7f4a_7c15_u64 as i64;

// ---------------------------------------------------------------------------
// Hash primitive
// ---------------------------------------------------------------------------

/// splitmix64 finalizer — bijective 64→64 bit mixer.
/// See module docs for full reference.
#[inline(always)]
fn splitmix64(mut x: u64) -> u64 {
    x ^= x >> 30;
    x = x.wrapping_mul(0xbf58_476d_1ce4_e5b9);
    x ^= x >> 27;
    x = x.wrapping_mul(0x94d0_49bb_1331_11eb);
    x ^= x >> 31;
    x
}

// ---------------------------------------------------------------------------
// Validity bitmap helpers
// ---------------------------------------------------------------------------

/// Check whether element `i` is valid (Arrow LSB bitmap, ABI §4.1).
/// When `vp` is null (`vp as usize == 0`), the column is all-valid.
#[inline(always)]
unsafe fn is_valid(vp: *const u8, i: usize) -> bool {
    if vp as usize == 0 {
        return true;
    }
    ((*vp.add(i >> 3)) >> (i & 7)) & 1 != 0
}

// ---------------------------------------------------------------------------
// Hash-table slot accessors (16-byte slots, caller-zeroed)
// ---------------------------------------------------------------------------

const SLOT_BYTES: usize = 16;

#[inline(always)]
unsafe fn slot_key(ht: *const u8, s: usize) -> i64 {
    (ht.add(s * SLOT_BYTES) as *const i64).read_unaligned()
}

#[inline(always)]
unsafe fn slot_val(ht: *const u8, s: usize) -> i32 {
    (ht.add(s * SLOT_BYTES + 8) as *const i32).read_unaligned()
}

#[inline(always)]
unsafe fn slot_occ(ht: *const u8, s: usize) -> i32 {
    (ht.add(s * SLOT_BYTES + 12) as *const i32).read_unaligned()
}

#[inline(always)]
unsafe fn set_slot(ht: *mut u8, s: usize, key: i64, val: i32, occ: i32) {
    let p = ht.add(s * SLOT_BYTES);
    (p as *mut i64).write_unaligned(key);
    (p.add(8) as *mut i32).write_unaligned(val);
    (p.add(12) as *mut i32).write_unaligned(occ);
}

// ---------------------------------------------------------------------------
// hash_dt — 64-bit hash over typed columns (ABI §9 D)
// ---------------------------------------------------------------------------

/// Hash a column of `i32` values.
///
/// Null rows (validity bit = 0) → `H_NULL`. Non-null rows → splitmix64(i64 of value).
#[no_mangle]
pub unsafe extern "C" fn hash_i32(
    data: *const i32,
    vp: *const u8,
    out_hash: *mut i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        *out_hash.add(i) = if is_valid(vp, i) {
            splitmix64(*data.add(i) as i64 as u64) as i64
        } else {
            H_NULL
        };
    }
}

/// Hash a column of `u32` values.
#[no_mangle]
pub unsafe extern "C" fn hash_u32(
    data: *const u32,
    vp: *const u8,
    out_hash: *mut i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        *out_hash.add(i) = if is_valid(vp, i) {
            splitmix64(*data.add(i) as u64) as i64
        } else {
            H_NULL
        };
    }
}

/// Hash a column of `f64` values.
///
/// Canonicalization (ABI §9 D):
/// - `-0.0` and `+0.0` are treated as equal → both hash to `+0.0` bits.
/// - All `NaN` bit patterns are treated as equal → all hash to the canonical quiet NaN.
#[no_mangle]
pub unsafe extern "C" fn hash_f64(
    data: *const f64,
    vp: *const u8,
    out_hash: *mut i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        *out_hash.add(i) = if is_valid(vp, i) {
            let v = *data.add(i);
            // Canonicalize: -0.0 → +0.0; any NaN → canonical quiet NaN
            let bits = if v == 0.0 {
                0u64 // +0.0
            } else if v.is_nan() {
                CANONICAL_F64_NAN_BITS
            } else {
                v.to_bits()
            };
            splitmix64(bits) as i64
        } else {
            H_NULL
        };
    }
}

/// Hash a column of `f32` values.
///
/// Same canonicalization as `hash_f64` but at f32 precision.
#[no_mangle]
pub unsafe extern "C" fn hash_f32(
    data: *const f32,
    vp: *const u8,
    out_hash: *mut i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        *out_hash.add(i) = if is_valid(vp, i) {
            let v = *data.add(i);
            let bits: u32 = if v == 0.0f32 {
                0u32 // +0.0f32
            } else if v.is_nan() {
                CANONICAL_F32_NAN_BITS
            } else {
                v.to_bits()
            };
            // Zero-extend the 32-bit value and hash
            splitmix64(bits as u64) as i64
        } else {
            H_NULL
        };
    }
}

// ---------------------------------------------------------------------------
// hash_combine — multi-key hash combination (ABI §9 D)
// ---------------------------------------------------------------------------

/// In-place multi-key hash combine: `acc[i] ^= mix(add[i])`.
///
/// Uses the boost::hash_combine formula (64-bit variant):
/// `acc ^= add + 0x9e3779b97f4a7c15 + (acc << 6) + (acc >> 2)`
///
/// This ensures that even if `acc` and `add` are equal, the combination
/// produces a different value than either input alone.
#[no_mangle]
pub unsafe extern "C" fn hash_combine(
    acc_hash: *mut i64,
    add_hash: *const i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        let acc = (*acc_hash.add(i)) as u64;
        let add = (*add_hash.add(i)) as u64;
        // boost-style hash_combine adapted to 64 bits
        let combined = acc
            ^ add
                .wrapping_add(0x9e37_79b9_7f4a_7c15_u64)
                .wrapping_add(acc << 6)
                .wrapping_add(acc >> 2);
        *acc_hash.add(i) = combined as i64;
    }
}

// ---------------------------------------------------------------------------
// group_build — assign dense group IDs in first-occurrence order (ABI §9 D)
// ---------------------------------------------------------------------------

/// Build a group-ID column from a pre-hashed key column.
///
/// Open-addressing hash table (`ht_ptr`, `ht_cap` slots, 16 bytes/slot,
/// caller-zeroed). Group IDs are assigned in **first-occurrence order**:
/// the first distinct hash seen becomes group 0, the second group 1, etc.
///
/// Returns `group_count` (≥ 0) on success, or `-1` if the table fills up
/// (caller should double `ht_cap`, re-zero, and re-call).
///
/// # Hash collisions
/// Groups are distinguished by their 64-bit hash value (ADR-005); accidental
/// hash collisions would merge two distinct keys into one group. The fixture
/// data is chosen to avoid such collisions; real data collision probability is
/// 2^-64 per pair.
#[no_mangle]
pub unsafe extern "C" fn group_build(
    hash_ptr: *const i64,
    len: u32,
    ht_ptr: *mut u8,
    ht_cap: u32,
    out_group_ids: *mut i32,
) -> i32 {
    let len = len as usize;
    let cap = ht_cap as usize;
    if cap == 0 {
        return if len == 0 { 0 } else { -1 };
    }
    let mut group_count: i32 = 0;

    for i in 0..len {
        let h = *hash_ptr.add(i);
        let start = (h as u64 % cap as u64) as usize;
        let mut s = start;
        let mut probes = 0usize;
        loop {
            if slot_occ(ht_ptr, s) == 0 {
                // Empty slot — this is a new group.
                set_slot(ht_ptr, s, h, group_count, 1);
                *out_group_ids.add(i) = group_count;
                group_count += 1;
                break;
            } else if slot_key(ht_ptr, s) == h {
                // Existing group with same hash.
                *out_group_ids.add(i) = slot_val(ht_ptr, s);
                break;
            }
            // Collision — linear probe.
            s = (s + 1) % cap;
            probes += 1;
            if probes >= cap {
                return -1; // table is full
            }
        }
    }

    group_count
}

// ---------------------------------------------------------------------------
// join_hash_inner — equi-join, inner variant (ABI §9 D)
// ---------------------------------------------------------------------------

/// Inner equi-join: build right, probe left.
///
/// **Protocol** (caller owns all buffers):
/// 1. Caller initialises `ht_ptr`/`ht_cap` (zeroed, power-of-two slots).
/// 2. Kernel builds on the right side (skipping null-validity right rows).
/// 3. Kernel probes left rows in order, collecting (l_idx, r_idx) pairs.
///    Null-validity left rows produce no output.
/// 4. Return value:
///    - `-1`: right side overflowed `ht_cap` → caller doubles cap, re-zeros, re-calls.
///    - `n`: total pair count. If `n > out_cap`, caller re-allocates out arrays to `n`
///      and re-calls (kernel re-runs both build and probe from scratch; result is
///      deterministic so this is correct).
///    - When `n ≤ out_cap`, all pairs have been written to `out_l_idx`/`out_r_idx`.
///
/// Duplicate right matches are emitted in build order (right-row insertion order).
#[no_mangle]
pub unsafe extern "C" fn join_hash_inner(
    lh_ptr: *const i64,
    l_vp: *const u8,
    l_len: u32,
    rh_ptr: *const i64,
    r_vp: *const u8,
    r_len: u32,
    ht_ptr: *mut u8,
    ht_cap: u32,
    out_l_idx: *mut i32,
    out_r_idx: *mut i32,
    out_cap: i32,
) -> i32 {
    let l_len = l_len as usize;
    let r_len = r_len as usize;
    let cap = ht_cap as usize;

    // ── Build phase: insert valid right rows ──────────────────────────────
    if cap > 0 {
        for r in 0..r_len {
            if !is_valid(r_vp, r) {
                continue; // null right rows are never matchable
            }
            let h = *rh_ptr.add(r);
            let start = (h as u64 % cap as u64) as usize;
            let mut s = start;
            let mut probes = 0usize;
            loop {
                if slot_occ(ht_ptr, s) == 0 {
                    set_slot(ht_ptr, s, h, r as i32, 1);
                    break;
                }
                s = (s + 1) % cap;
                probes += 1;
                if probes >= cap {
                    return -1; // table full
                }
            }
        }
    } else if r_len > 0 {
        return -1; // zero-capacity table can't hold any right rows
    }

    // ── Probe phase: scan left rows in order ─────────────────────────────
    let mut total: i32 = 0;
    for l in 0..l_len {
        if !is_valid(l_vp, l) {
            continue; // null left rows produce no output in inner join
        }
        if cap == 0 {
            continue; // empty right side → no matches
        }
        let h = *lh_ptr.add(l);
        let start = (h as u64 % cap as u64) as usize;
        let mut s = start;
        let mut probes = 0usize;
        loop {
            if slot_occ(ht_ptr, s) == 0 {
                break; // no more possible matches in this chain
            }
            if slot_key(ht_ptr, s) == h {
                // Match: emit (l, r_match)
                if total < out_cap {
                    *out_l_idx.add(total as usize) = l as i32;
                    *out_r_idx.add(total as usize) = slot_val(ht_ptr, s);
                }
                total += 1;
            }
            s = (s + 1) % cap;
            probes += 1;
            if probes >= cap {
                break; // safety: full table scan
            }
        }
    }

    total
}

// ---------------------------------------------------------------------------
// join_hash_left — equi-join, left outer variant (ABI §9 D)
// ---------------------------------------------------------------------------

/// Left outer equi-join: build right, probe left.
///
/// Same protocol as `join_hash_inner`, with one difference:
/// - Unmatched left rows **and** null-validity left rows emit `(l_idx, -1)`.
///   (The frame layer turns a `-1` right index into a null-gather for that row.)
#[no_mangle]
pub unsafe extern "C" fn join_hash_left(
    lh_ptr: *const i64,
    l_vp: *const u8,
    l_len: u32,
    rh_ptr: *const i64,
    r_vp: *const u8,
    r_len: u32,
    ht_ptr: *mut u8,
    ht_cap: u32,
    out_l_idx: *mut i32,
    out_r_idx: *mut i32,
    out_cap: i32,
) -> i32 {
    let l_len = l_len as usize;
    let r_len = r_len as usize;
    let cap = ht_cap as usize;

    // ── Build phase: same as inner join ──────────────────────────────────
    if cap > 0 {
        for r in 0..r_len {
            if !is_valid(r_vp, r) {
                continue;
            }
            let h = *rh_ptr.add(r);
            let start = (h as u64 % cap as u64) as usize;
            let mut s = start;
            let mut probes = 0usize;
            loop {
                if slot_occ(ht_ptr, s) == 0 {
                    set_slot(ht_ptr, s, h, r as i32, 1);
                    break;
                }
                s = (s + 1) % cap;
                probes += 1;
                if probes >= cap {
                    return -1;
                }
            }
        }
    } else if r_len > 0 {
        return -1;
    }

    // ── Probe phase: null/unmatched left rows emit (l, -1) ───────────────
    let mut total: i32 = 0;
    for l in 0..l_len {
        // Null-validity left rows: always emit (l, -1) in left join.
        if !is_valid(l_vp, l) {
            if total < out_cap {
                *out_l_idx.add(total as usize) = l as i32;
                *out_r_idx.add(total as usize) = -1;
            }
            total += 1;
            continue;
        }

        if cap == 0 {
            // No right side at all → unmatched
            if total < out_cap {
                *out_l_idx.add(total as usize) = l as i32;
                *out_r_idx.add(total as usize) = -1;
            }
            total += 1;
            continue;
        }

        let h = *lh_ptr.add(l);
        let start = (h as u64 % cap as u64) as usize;
        let mut s = start;
        let mut probes = 0usize;
        let mut matched = false;
        loop {
            if slot_occ(ht_ptr, s) == 0 {
                break; // end of probe chain
            }
            if slot_key(ht_ptr, s) == h {
                matched = true;
                if total < out_cap {
                    *out_l_idx.add(total as usize) = l as i32;
                    *out_r_idx.add(total as usize) = slot_val(ht_ptr, s);
                }
                total += 1;
            }
            s = (s + 1) % cap;
            probes += 1;
            if probes >= cap {
                break;
            }
        }

        if !matched {
            // Unmatched valid left row: emit (l, -1)
            if total < out_cap {
                *out_l_idx.add(total as usize) = l as i32;
                *out_r_idx.add(total as usize) = -1;
            }
            total += 1;
        }
    }

    total
}

// ========================================================================
// § i64 hash kernel (v2.3) — wasm-abi.md §10
// ========================================================================

/// Hash a column of `i64` values.
///
/// Non-null: `splitmix64(value as u64) as i64`.
/// Null: `H_NULL`.
#[no_mangle]
pub unsafe extern "C" fn hash_i64(
    data: *const i64,
    vp: *const u8,
    out_hash: *mut i64,
    len: u32,
) {
    let len = len as usize;
    for i in 0..len {
        *out_hash.add(i) = if is_valid(vp, i) {
            splitmix64(*data.add(i) as u64) as i64
        } else {
            H_NULL
        };
    }
}
