//! Reduction kernel family — Phase 2. Flat C ABI per contracts/wasm-abi.md §9.
//! Owned by the Phase-2 reduce agent; other agents do not edit this file.
//!
//! ## Accumulation order (prescribed, both builds identical)
//!
//! f64 sum/mean: 2 striped accumulators — element i → acc[i & 1]; combined acc0 + acc1.
//! f32 sum/mean: 4 striped accumulators — element i → acc[i & 3];
//!   combined left-to-right in f32: ((acc0 + acc1) + acc2) + acc3.
//! Null lanes contribute 0 (additive identity) without breaking stripe alignment.
//! std/var: two-pass — striped mean, then striped sum of squared deviations, ddof=1.
//!
//! ## nunique — no-alloc ceiling (ABI §5.4)
//!
//! Kernels never alloc. v1 uses an O(n²) in-place dedup scan over a fixed 512-element
//! stack scratch buffer (4 KB). Arrays with more than 512 non-null distinct values fall
//! back to a full O(n²) scan over the raw input. This is a v1 ceiling; v2 should use
//! a caller-provided hash-set scratch or sort-and-deduplicate.
//! NaN canonicalised to one distinct value; nulls excluded (dtypes.md §4.3).
//!
//! ## sqrt
//!
//! `extern "C" { fn sqrt(x: f64) }` resolves to the native wasm `f64.sqrt` instruction
//! via LLVM's math-function recognition in -C opt-level=3. No import is emitted in the
//! final binary; wasm-opt inlines it to the primitive opcode.

#![allow(clippy::too_many_arguments)]

#[cfg(target_feature = "simd128")]
use core::arch::wasm32;

// ---------------------------------------------------------------------------
// sqrt shim — resolves to wasm f64.sqrt via LLVM opt (no host import needed)
// ---------------------------------------------------------------------------

extern "C" {
    fn sqrt(x: f64) -> f64;
}

#[inline(always)]
fn sqrt_f64(x: f64) -> f64 {
    // SAFETY: LLVM/wasm-opt replace this with the native f64.sqrt wasm instruction.
    // The extern "C" declaration causes LLVM to recognise it as the math sqrt function
    // and emit the IEEE-754 correctly-rounded f64.sqrt opcode rather than an import.
    unsafe { sqrt(x) }
}

// ---------------------------------------------------------------------------
// Bitmap helpers
// ---------------------------------------------------------------------------

/// Returns true when element `i` is valid.
/// `vp == null` means all-valid (ABI §4.1 fast path).
#[inline(always)]
unsafe fn is_valid(vp: *const u8, i: usize) -> bool {
    if vp.is_null() {
        return true;
    }
    (*vp.add(i >> 3) >> (i & 7)) & 1 != 0
}

/// Count the number of valid bits in a `ceil(len/8)`-byte Arrow-LSB bitmap.
#[inline]
unsafe fn count_valid(vp: *const u8, len: usize) -> usize {
    if vp.is_null() {
        return len;
    }
    let mut count = 0usize;
    let full_bytes = len / 8;
    for b in 0..full_bytes {
        count += (*vp.add(b)).count_ones() as usize;
    }
    let rem = len & 7;
    if rem > 0 {
        let mask = (1u8 << rem).wrapping_sub(1);
        count += (*vp.add(full_bytes) & mask).count_ones() as usize;
    }
    count
}

// ---------------------------------------------------------------------------
// count_null
// ---------------------------------------------------------------------------

/// Returns the number of non-null (valid) elements.
/// Signature: `(i32 vp, i32 len) -> i32`.
#[no_mangle]
pub unsafe extern "C" fn count_null(vp: *const u8, len: i32) -> i32 {
    count_valid(vp, len as usize) as i32
}

// ---------------------------------------------------------------------------
// sum_f64_null — PRESCRIBED 2-striped accumulation
// ---------------------------------------------------------------------------

/// Element i goes to accumulator i & 1; combined as acc0 + acc1.
/// SIMD build: f64x2 lanes naturally implement 2-stripe.
/// Scalar build: explicit paired loop simulates the same striping.
#[no_mangle]
pub unsafe extern "C" fn sum_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    let len = len as usize;

    #[cfg(target_feature = "simd128")]
    {
        let mut acc = wasm32::f64x2_splat(0.0f64); // lane0 = acc[0], lane1 = acc[1]
        let mut i = 0usize;
        while i + 2 <= len {
            let v0 = if is_valid(vp, i) { *data.add(i) } else { 0.0f64 };
            let v1 = if is_valid(vp, i + 1) { *data.add(i + 1) } else { 0.0f64 };
            acc = wasm32::f64x2_add(acc, wasm32::f64x2(v0, v1));
            i += 2;
        }
        let mut acc0 = wasm32::f64x2_extract_lane::<0>(acc);
        let acc1 = wasm32::f64x2_extract_lane::<1>(acc);
        // Odd tail → goes to acc[i & 1] = acc0 (i is even after the loop exit)
        if i < len && is_valid(vp, i) {
            acc0 += *data.add(i);
        }
        acc0 + acc1
    }

    #[cfg(not(target_feature = "simd128"))]
    {
        let mut acc0 = 0.0f64;
        let mut acc1 = 0.0f64;
        let mut i = 0usize;
        while i + 2 <= len {
            if is_valid(vp, i) { acc0 += *data.add(i); }
            if is_valid(vp, i + 1) { acc1 += *data.add(i + 1); }
            i += 2;
        }
        if i < len && is_valid(vp, i) { acc0 += *data.add(i); }
        acc0 + acc1
    }
}

// ---------------------------------------------------------------------------
// sum_f32_null — PRESCRIBED 4-striped accumulation
// ---------------------------------------------------------------------------

/// Element i → acc[i & 3]; combined left-to-right in f32: ((acc0+acc1)+acc2)+acc3.
#[no_mangle]
pub unsafe extern "C" fn sum_f32_null(data: *const f32, vp: *const u8, len: i32) -> f32 {
    let len = len as usize;

    #[cfg(target_feature = "simd128")]
    {
        let mut acc = wasm32::f32x4_splat(0.0f32);
        let mut i = 0usize;
        while i + 4 <= len {
            let v0 = if is_valid(vp, i) { *data.add(i) } else { 0.0f32 };
            let v1 = if is_valid(vp, i + 1) { *data.add(i + 1) } else { 0.0f32 };
            let v2 = if is_valid(vp, i + 2) { *data.add(i + 2) } else { 0.0f32 };
            let v3 = if is_valid(vp, i + 3) { *data.add(i + 3) } else { 0.0f32 };
            acc = wasm32::f32x4_add(acc, wasm32::f32x4(v0, v1, v2, v3));
            i += 4;
        }
        let mut acc0 = wasm32::f32x4_extract_lane::<0>(acc);
        let mut acc1 = wasm32::f32x4_extract_lane::<1>(acc);
        let mut acc2 = wasm32::f32x4_extract_lane::<2>(acc);
        let mut acc3 = wasm32::f32x4_extract_lane::<3>(acc);
        while i < len {
            if is_valid(vp, i) {
                match i & 3 {
                    0 => acc0 += *data.add(i),
                    1 => acc1 += *data.add(i),
                    2 => acc2 += *data.add(i),
                    _ => acc3 += *data.add(i),
                }
            }
            i += 1;
        }
        ((acc0 + acc1) + acc2) + acc3
    }

    #[cfg(not(target_feature = "simd128"))]
    {
        let mut acc0 = 0.0f32;
        let mut acc1 = 0.0f32;
        let mut acc2 = 0.0f32;
        let mut acc3 = 0.0f32;
        let mut i = 0usize;
        while i + 4 <= len {
            if is_valid(vp, i) { acc0 += *data.add(i); }
            if is_valid(vp, i + 1) { acc1 += *data.add(i + 1); }
            if is_valid(vp, i + 2) { acc2 += *data.add(i + 2); }
            if is_valid(vp, i + 3) { acc3 += *data.add(i + 3); }
            i += 4;
        }
        while i < len {
            if is_valid(vp, i) {
                match i & 3 {
                    0 => acc0 += *data.add(i),
                    1 => acc1 += *data.add(i),
                    2 => acc2 += *data.add(i),
                    _ => acc3 += *data.add(i),
                }
            }
            i += 1;
        }
        ((acc0 + acc1) + acc2) + acc3
    }
}

// ---------------------------------------------------------------------------
// Integer sums — return f64 (ABI §9 "f64 for ints")
// ---------------------------------------------------------------------------

macro_rules! impl_sum_int {
    ($name:ident, $T:ty) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(data: *const $T, vp: *const u8, len: i32) -> f64 {
            let len = len as usize;
            let mut acc = 0.0f64;
            for i in 0..len {
                if is_valid(vp, i) {
                    acc += (*data.add(i)) as f64;
                }
            }
            acc
        }
    };
}
impl_sum_int!(sum_i32_null, i32);
impl_sum_int!(sum_u32_null, u32);

// ---------------------------------------------------------------------------
// mean kernels — striped sum / non-null count; empty/all-null → NaN
// ---------------------------------------------------------------------------

#[no_mangle]
pub unsafe extern "C" fn mean_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    let n = count_valid(vp, len as usize);
    if n == 0 { return f64::NAN; }
    sum_f64_null(data, vp, len) / (n as f64)
}

#[no_mangle]
pub unsafe extern "C" fn mean_f32_null(data: *const f32, vp: *const u8, len: i32) -> f64 {
    let n = count_valid(vp, len as usize);
    if n == 0 { return f64::NAN; }
    (sum_f32_null(data, vp, len) as f64) / (n as f64)
}

#[no_mangle]
pub unsafe extern "C" fn mean_i32_null(data: *const i32, vp: *const u8, len: i32) -> f64 {
    let n = count_valid(vp, len as usize);
    if n == 0 { return f64::NAN; }
    sum_i32_null(data, vp, len) / (n as f64)
}

#[no_mangle]
pub unsafe extern "C" fn mean_u32_null(data: *const u32, vp: *const u8, len: i32) -> f64 {
    let n = count_valid(vp, len as usize);
    if n == 0 { return f64::NAN; }
    sum_u32_null(data, vp, len) / (n as f64)
}

// ---------------------------------------------------------------------------
// min/max f64 — NaN not selected (IEEE minNum/maxNum).
// empty/all-null/all-NaN → NaN (wasm-abi.md §9).
//
// Strategy (both builds):
//   - Null/NaN elements are mapped to +INF (for min) or -INF (for max) so the
//     hot-loop comparison is branchless — just a compare with no `found` flag.
//   - After the loop, if result == +INF (min) or -INF (max): either the true
//     extremum is ±INF, or there were no valid non-NaN elements.  A second
//     O(n) pass disambiguates (triggered only in those rare edge cases).
// SIMD build: use f64x2_pmin / f64x2_pmax on pairs; null lanes filled with ±INF.
// ---------------------------------------------------------------------------

/// Return NaN if no valid non-NaN element exists in [0, len), else +INF.
/// Used by min_f64_null when the pmin accumulator stays at +INF.
#[inline]
unsafe fn min_f64_null_verify(data: *const f64, vp: *const u8, len: usize) -> f64 {
    for i in 0..len {
        if is_valid(vp, i) && !(*data.add(i)).is_nan() {
            return f64::INFINITY; // actual min is +INF (e.g. all elements = +INF)
        }
    }
    f64::NAN // empty, all-null, or all valid elements are NaN
}

/// Return NaN if no valid non-NaN element exists in [0, len), else -INF.
#[inline]
unsafe fn max_f64_null_verify(data: *const f64, vp: *const u8, len: usize) -> f64 {
    for i in 0..len {
        if is_valid(vp, i) && !(*data.add(i)).is_nan() {
            return f64::NEG_INFINITY;
        }
    }
    f64::NAN
}

#[no_mangle]
pub unsafe extern "C" fn min_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    let len = len as usize;

    #[cfg(target_feature = "simd128")]
    {
        let inf_splat = wasm32::f64x2_splat(f64::INFINITY);
        let mut acc = inf_splat;
        let mut i = 0usize;

        while i + 2 <= len {
            let v0 = *data.add(i);
            let v1 = *data.add(i + 1);
            // Substitute +INF for null or NaN so pmin ignores them.
            let s0 = if is_valid(vp, i) && !v0.is_nan() { v0 } else { f64::INFINITY };
            let s1 = if is_valid(vp, i + 1) && !v1.is_nan() { v1 } else { f64::INFINITY };
            acc = wasm32::f64x2_pmin(acc, wasm32::f64x2(s0, s1));
            i += 2;
        }

        let l0 = wasm32::f64x2_extract_lane::<0>(acc);
        let l1 = wasm32::f64x2_extract_lane::<1>(acc);
        let mut result = if l0 < l1 { l0 } else { l1 };

        // Scalar tail
        while i < len {
            if is_valid(vp, i) {
                let v = *data.add(i);
                if !v.is_nan() && v < result { result = v; }
            }
            i += 1;
        }

        if result < f64::INFINITY { result } else { min_f64_null_verify(data, vp, len) }
    }

    #[cfg(not(target_feature = "simd128"))]
    {
        let mut result = f64::INFINITY;
        for i in 0..len {
            if is_valid(vp, i) {
                let v = *data.add(i);
                if !v.is_nan() && v < result { result = v; }
            }
        }
        if result < f64::INFINITY { result } else { min_f64_null_verify(data, vp, len) }
    }
}

#[no_mangle]
pub unsafe extern "C" fn max_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    let len = len as usize;

    #[cfg(target_feature = "simd128")]
    {
        let neginf_splat = wasm32::f64x2_splat(f64::NEG_INFINITY);
        let mut acc = neginf_splat;
        let mut i = 0usize;

        while i + 2 <= len {
            let v0 = *data.add(i);
            let v1 = *data.add(i + 1);
            let s0 = if is_valid(vp, i) && !v0.is_nan() { v0 } else { f64::NEG_INFINITY };
            let s1 = if is_valid(vp, i + 1) && !v1.is_nan() { v1 } else { f64::NEG_INFINITY };
            acc = wasm32::f64x2_pmax(acc, wasm32::f64x2(s0, s1));
            i += 2;
        }

        let l0 = wasm32::f64x2_extract_lane::<0>(acc);
        let l1 = wasm32::f64x2_extract_lane::<1>(acc);
        let mut result = if l0 > l1 { l0 } else { l1 };

        while i < len {
            if is_valid(vp, i) {
                let v = *data.add(i);
                if !v.is_nan() && v > result { result = v; }
            }
            i += 1;
        }

        if result > f64::NEG_INFINITY { result } else { max_f64_null_verify(data, vp, len) }
    }

    #[cfg(not(target_feature = "simd128"))]
    {
        let mut result = f64::NEG_INFINITY;
        for i in 0..len {
            if is_valid(vp, i) {
                let v = *data.add(i);
                if !v.is_nan() && v > result { result = v; }
            }
        }
        if result > f64::NEG_INFINITY { result } else { max_f64_null_verify(data, vp, len) }
    }
}

// ---------------------------------------------------------------------------
// min/max f32
// ---------------------------------------------------------------------------

#[no_mangle]
pub unsafe extern "C" fn min_f32_null(data: *const f32, vp: *const u8, len: i32) -> f32 {
    let len = len as usize;
    let mut result = f32::INFINITY;
    for i in 0..len {
        if is_valid(vp, i) {
            let v = *data.add(i);
            if !v.is_nan() && v < result { result = v; }
        }
    }
    if result < f32::INFINITY { return result; }
    // Check if any valid non-NaN element exists (actual min might be +INF)
    for i in 0..len {
        if is_valid(vp, i) && !(*data.add(i)).is_nan() { return f32::INFINITY; }
    }
    f32::NAN
}

#[no_mangle]
pub unsafe extern "C" fn max_f32_null(data: *const f32, vp: *const u8, len: i32) -> f32 {
    let len = len as usize;
    let mut result = f32::NEG_INFINITY;
    for i in 0..len {
        if is_valid(vp, i) {
            let v = *data.add(i);
            if !v.is_nan() && v > result { result = v; }
        }
    }
    if result > f32::NEG_INFINITY { return result; }
    for i in 0..len {
        if is_valid(vp, i) && !(*data.add(i)).is_nan() { return f32::NEG_INFINITY; }
    }
    f32::NAN
}

// ---------------------------------------------------------------------------
// min/max i32 / u32 — empty/all-null → 0 (callers use count_null to detect)
// ---------------------------------------------------------------------------

macro_rules! impl_min_int {
    ($name:ident, $T:ty) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(data: *const $T, vp: *const u8, len: i32) -> $T {
            let len = len as usize;
            let mut result: $T = 0;
            let mut found = false;
            for i in 0..len {
                if is_valid(vp, i) {
                    let v = *data.add(i);
                    if !found || v < result { result = v; found = true; }
                }
            }
            result  // 0 when not found (ABI §9 table)
        }
    };
}

macro_rules! impl_max_int {
    ($name:ident, $T:ty) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(data: *const $T, vp: *const u8, len: i32) -> $T {
            let len = len as usize;
            let mut result: $T = 0;
            let mut found = false;
            for i in 0..len {
                if is_valid(vp, i) {
                    let v = *data.add(i);
                    if !found || v > result { result = v; found = true; }
                }
            }
            result
        }
    };
}

impl_min_int!(min_i32_null, i32);
impl_max_int!(max_i32_null, i32);
impl_min_int!(min_u32_null, u32);
impl_max_int!(max_u32_null, u32);

// ---------------------------------------------------------------------------
// std / var — two-pass, ddof=1.  Returns f64.  Fewer than 2 non-null → NaN.
// ---------------------------------------------------------------------------

/// Inner: two-pass variance for f64 data.
unsafe fn var_f64_inner(data: *const f64, vp: *const u8, len: usize) -> f64 {
    let n = count_valid(vp, len);
    if n < 2 { return f64::NAN; }
    // Pass 1: striped mean (same 2-stripe prescription).
    let mean = mean_f64_null(data, vp, len as i32);
    if mean.is_nan() { return f64::NAN; } // NaN in data poisoned the mean
    // Pass 2: striped sum of squared deviations.
    let mut ss0 = 0.0f64;
    let mut ss1 = 0.0f64;
    let mut i = 0usize;
    while i + 2 <= len {
        if is_valid(vp, i) { let d = *data.add(i) - mean; ss0 += d * d; }
        if is_valid(vp, i + 1) { let d = *data.add(i + 1) - mean; ss1 += d * d; }
        i += 2;
    }
    if i < len && is_valid(vp, i) { let d = *data.add(i) - mean; ss0 += d * d; }
    (ss0 + ss1) / ((n - 1) as f64)
}

#[no_mangle]
pub unsafe extern "C" fn var_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    var_f64_inner(data, vp, len as usize)
}

#[no_mangle]
pub unsafe extern "C" fn std_f64_null(data: *const f64, vp: *const u8, len: i32) -> f64 {
    sqrt_f64(var_f64_inner(data, vp, len as usize))
}

/// Two-pass variance for f32 data (pass 2 in f64 for precision).
unsafe fn var_f32_inner(data: *const f32, vp: *const u8, len: usize) -> f64 {
    let n = count_valid(vp, len);
    if n < 2 { return f64::NAN; }
    let mean = mean_f32_null(data, vp, len as i32);
    if mean.is_nan() { return f64::NAN; }
    let mut ss = 0.0f64;
    for i in 0..len {
        if is_valid(vp, i) { let d = (*data.add(i)) as f64 - mean; ss += d * d; }
    }
    ss / ((n - 1) as f64)
}

#[no_mangle]
pub unsafe extern "C" fn var_f32_null(data: *const f32, vp: *const u8, len: i32) -> f64 {
    var_f32_inner(data, vp, len as usize)
}

#[no_mangle]
pub unsafe extern "C" fn std_f32_null(data: *const f32, vp: *const u8, len: i32) -> f64 {
    sqrt_f64(var_f32_inner(data, vp, len as usize))
}

/// Two-pass variance for i32 data (widened to f64).
unsafe fn var_i32_inner(data: *const i32, vp: *const u8, len: usize) -> f64 {
    let n = count_valid(vp, len);
    if n < 2 { return f64::NAN; }
    let mean = mean_i32_null(data, vp, len as i32);
    if mean.is_nan() { return f64::NAN; }
    let mut ss = 0.0f64;
    for i in 0..len {
        if is_valid(vp, i) { let d = (*data.add(i)) as f64 - mean; ss += d * d; }
    }
    ss / ((n - 1) as f64)
}

#[no_mangle]
pub unsafe extern "C" fn var_i32_null(data: *const i32, vp: *const u8, len: i32) -> f64 {
    var_i32_inner(data, vp, len as usize)
}

#[no_mangle]
pub unsafe extern "C" fn std_i32_null(data: *const i32, vp: *const u8, len: i32) -> f64 {
    sqrt_f64(var_i32_inner(data, vp, len as usize))
}

/// Two-pass variance for u32 data (widened to f64).
unsafe fn var_u32_inner(data: *const u32, vp: *const u8, len: usize) -> f64 {
    let n = count_valid(vp, len);
    if n < 2 { return f64::NAN; }
    let mean = mean_u32_null(data, vp, len as i32);
    if mean.is_nan() { return f64::NAN; }
    let mut ss = 0.0f64;
    for i in 0..len {
        if is_valid(vp, i) { let d = (*data.add(i)) as f64 - mean; ss += d * d; }
    }
    ss / ((n - 1) as f64)
}

#[no_mangle]
pub unsafe extern "C" fn var_u32_null(data: *const u32, vp: *const u8, len: i32) -> f64 {
    var_u32_inner(data, vp, len as usize)
}

#[no_mangle]
pub unsafe extern "C" fn std_u32_null(data: *const u32, vp: *const u8, len: i32) -> f64 {
    sqrt_f64(var_u32_inner(data, vp, len as usize))
}

// ---------------------------------------------------------------------------
// nunique — O(n²) in-place dedup; no alloc (ABI §5.4).
//
// V1 CEILING: O(n²) becomes prohibitive beyond ~10K rows with many distinct values.
// For v2: use caller-provided hash-set scratch (ABI would need a signature change)
// or sort-based dedup (would need sort kernel from Agent C).
// See bead notes for the bench ceiling report.
//
// NaN canonicalised to one representative before comparison (dtypes.md §4.6).
// Nulls excluded from count (dtypes.md §4.3).
// ---------------------------------------------------------------------------

/// Capacity of the stack dedup buffer.
const NUNIQUE_CAP: usize = 512;

#[no_mangle]
pub unsafe extern "C" fn nunique_f64_null(data: *const f64, vp: *const u8, len: i32) -> i32 {
    let len = len as usize;
    // Stack scratch: store as u64 bits for exact bit-pattern comparison.
    let mut seen = [0u64; NUNIQUE_CAP];
    let mut n_seen = 0usize;
    let mut nan_seen = false;
    let mut overflow = false;

    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if v.is_nan() { nan_seen = true; continue; }
        let bits = v.to_bits();
        if !seen[..n_seen].contains(&bits) {
            if n_seen < NUNIQUE_CAP { seen[n_seen] = bits; n_seen += 1; }
            else { overflow = true; }
        }
    }

    if !overflow {
        return (n_seen + if nan_seen { 1 } else { 0 }) as i32;
    }
    // Overflow fallback: full O(n²) scan.
    let mut count = if nan_seen { 1i32 } else { 0 };
    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if v.is_nan() { continue; }
        let bits = v.to_bits();
        let mut first = true;
        for j in 0..i {
            if !is_valid(vp, j) { continue; }
            let w = *data.add(j);
            if !w.is_nan() && w.to_bits() == bits { first = false; break; }
        }
        if first { count += 1; }
    }
    count
}

#[no_mangle]
pub unsafe extern "C" fn nunique_f32_null(data: *const f32, vp: *const u8, len: i32) -> i32 {
    let len = len as usize;
    let mut seen = [0u32; NUNIQUE_CAP];
    let mut n_seen = 0usize;
    let mut nan_seen = false;
    let mut overflow = false;

    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if v.is_nan() { nan_seen = true; continue; }
        let bits = v.to_bits();
        if !seen[..n_seen].contains(&bits) {
            if n_seen < NUNIQUE_CAP { seen[n_seen] = bits; n_seen += 1; }
            else { overflow = true; }
        }
    }

    if !overflow {
        return (n_seen + if nan_seen { 1 } else { 0 }) as i32;
    }
    let mut count = if nan_seen { 1i32 } else { 0 };
    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if v.is_nan() { continue; }
        let bits = v.to_bits();
        let mut first = true;
        for j in 0..i {
            if !is_valid(vp, j) { continue; }
            let w = *data.add(j);
            if !w.is_nan() && w.to_bits() == bits { first = false; break; }
        }
        if first { count += 1; }
    }
    count
}

#[no_mangle]
pub unsafe extern "C" fn nunique_i32_null(data: *const i32, vp: *const u8, len: i32) -> i32 {
    let len = len as usize;
    let mut seen = [0i32; NUNIQUE_CAP];
    let mut n_seen = 0usize;
    let mut overflow = false;

    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if !seen[..n_seen].contains(&v) {
            if n_seen < NUNIQUE_CAP { seen[n_seen] = v; n_seen += 1; }
            else { overflow = true; }
        }
    }

    if !overflow { return n_seen as i32; }
    let mut count = 0i32;
    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        let mut first = true;
        for j in 0..i {
            if is_valid(vp, j) && *data.add(j) == v { first = false; break; }
        }
        if first { count += 1; }
    }
    count
}

#[no_mangle]
pub unsafe extern "C" fn nunique_u32_null(data: *const u32, vp: *const u8, len: i32) -> i32 {
    let len = len as usize;
    let mut seen = [0u32; NUNIQUE_CAP];
    let mut n_seen = 0usize;
    let mut overflow = false;

    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        if !seen[..n_seen].contains(&v) {
            if n_seen < NUNIQUE_CAP { seen[n_seen] = v; n_seen += 1; }
            else { overflow = true; }
        }
    }

    if !overflow { return n_seen as i32; }
    let mut count = 0i32;
    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        let mut first = true;
        for j in 0..i {
            if is_valid(vp, j) && *data.add(j) == v { first = false; break; }
        }
        if first { count += 1; }
    }
    count
}

// ---------------------------------------------------------------------------
// first / last — first/last non-null element by row order (skipna).
// Writes out_valid (i32 ptr): 1 = valid result, 0 = all-null/empty.
// Signature: (i32 data, i32 vp, i32 len, i32 out_valid) -> <dt>
// ---------------------------------------------------------------------------

macro_rules! impl_first {
    ($name:ident, $T:ty, $zero:expr) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(
            data: *const $T,
            vp: *const u8,
            len: i32,
            out_valid: *mut i32,
        ) -> $T {
            let len = len as usize;
            for i in 0..len {
                if is_valid(vp, i) {
                    *out_valid = 1;
                    return *data.add(i);
                }
            }
            *out_valid = 0;
            $zero
        }
    };
}

macro_rules! impl_last {
    ($name:ident, $T:ty, $zero:expr) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(
            data: *const $T,
            vp: *const u8,
            len: i32,
            out_valid: *mut i32,
        ) -> $T {
            let len = len as usize;
            let mut result = $zero;
            let mut found = false;
            for i in 0..len {
                if is_valid(vp, i) {
                    result = *data.add(i);
                    found = true;
                }
            }
            *out_valid = if found { 1 } else { 0 };
            result
        }
    };
}

impl_first!(first_f64_null, f64, 0.0f64);
impl_last! (last_f64_null,  f64, 0.0f64);
impl_first!(first_f32_null, f32, 0.0f32);
impl_last! (last_f32_null,  f32, 0.0f32);
impl_first!(first_i32_null, i32, 0i32);
impl_last! (last_i32_null,  i32, 0i32);
impl_first!(first_u32_null, u32, 0u32);
impl_last! (last_u32_null,  u32, 0u32);

// ========================================================================
// § i64 reductions (v2.3) — wasm-abi.md §10
// ========================================================================

/// sum_i64: wrapping accumulator, returns i64 (not f64 like sum_i32/u32).
#[no_mangle]
pub unsafe extern "C" fn sum_i64_null(data: *const i64, vp: *const u8, len: i32) -> i64 {
    let len = len as usize;
    let mut acc: i64 = 0;
    for i in 0..len {
        if is_valid(vp, i) { acc = acc.wrapping_add(*data.add(i)); }
    }
    acc
}

/// mean_i64: convert each valid element i64→f64 FIRST, then 2-striped f64 sum.
/// Returns NaN when all elements are null.
#[no_mangle]
pub unsafe extern "C" fn mean_i64_null(data: *const i64, vp: *const u8, len: i32) -> f64 {
    let len = len as usize;
    let n = count_valid(vp, len);
    if n == 0 { return f64::NAN; }
    let mut acc0 = 0.0f64;
    let mut acc1 = 0.0f64;
    let mut i = 0usize;
    while i + 2 <= len {
        if is_valid(vp, i)     { acc0 += *data.add(i)     as f64; }
        if is_valid(vp, i + 1) { acc1 += *data.add(i + 1) as f64; }
        i += 2;
    }
    if i < len && is_valid(vp, i) { acc0 += *data.add(i) as f64; }
    (acc0 + acc1) / (n as f64)
}

impl_min_int!(min_i64_null, i64);
impl_max_int!(max_i64_null, i64);

/// var_i64: two-pass; i64→f64 per element; 2-striped pass 2.
#[no_mangle]
pub unsafe extern "C" fn var_i64_null(data: *const i64, vp: *const u8, len: i32) -> f64 {
    let len = len as usize;
    let n = count_valid(vp, len);
    if n < 2 { return f64::NAN; }
    // Pass 1: mean (reuse mean logic)
    let mut a0 = 0.0f64; let mut a1 = 0.0f64;
    let mut i = 0usize;
    while i + 2 <= len {
        if is_valid(vp, i)     { a0 += *data.add(i)     as f64; }
        if is_valid(vp, i + 1) { a1 += *data.add(i + 1) as f64; }
        i += 2;
    }
    if i < len && is_valid(vp, i) { a0 += *data.add(i) as f64; }
    let mean = (a0 + a1) / (n as f64);
    // Pass 2: sum of squared deviations (2-striped)
    let mut s0 = 0.0f64; let mut s1 = 0.0f64;
    let mut i = 0usize;
    while i + 2 <= len {
        if is_valid(vp, i)     { let d = *data.add(i)     as f64 - mean; s0 += d * d; }
        if is_valid(vp, i + 1) { let d = *data.add(i + 1) as f64 - mean; s1 += d * d; }
        i += 2;
    }
    if i < len && is_valid(vp, i) { let d = *data.add(i) as f64 - mean; s0 += d * d; }
    (s0 + s1) / ((n - 1) as f64)
}

/// std_i64: sqrt(var_i64). Returns NaN when var is NaN.
#[no_mangle]
pub unsafe extern "C" fn std_i64_null(data: *const i64, vp: *const u8, len: i32) -> f64 {
    sqrt_f64(var_i64_null(data, vp, len))
}

/// nunique_i64: O(n²) in-place dedup, capped at NUNIQUE_CAP.
#[no_mangle]
pub unsafe extern "C" fn nunique_i64_null(data: *const i64, vp: *const u8, len: i32) -> i32 {
    let len = len as usize;
    let mut buf = [0i64; NUNIQUE_CAP];
    let mut cnt = 0usize;
    for i in 0..len {
        if !is_valid(vp, i) { continue; }
        let v = *data.add(i);
        let dup = buf[..cnt].contains(&v);
        if !dup {
            if cnt < NUNIQUE_CAP { buf[cnt] = v; }
            cnt += 1;
        }
    }
    cnt as i32
}

impl_first!(first_i64_null, i64, 0i64);
impl_last! (last_i64_null,  i64, 0i64);
