//! select kernel family — Phase 2. Flat C ABI per contracts/wasm-abi.md §9.
//! Owned by Phase-2 Agent C; other agents do not edit this file.
//!
//! ## Exports
//!
//! | export              | signature                                                          |
//! |---------------------|--------------------------------------------------------------------|
//! | `filter_dt`         | `(data, mask, out, len)->i32` (compacts, returns count)            |
//! | `filter_indices`    | `(mask, out_idx, len)->i32` (kept compiled; JS dispatch in index.ts)|
//! | `gather_dt`         | `(data, idx, idx_len, out)->()`                                    |
//! | `gather_validity`   | `(vp, idx, idx_len, out_vp)->()`                                   |
//! | `argsort_dt`        | `(data, vp, inout_perm, len, desc, scratch_ptr)->()` (ABI v1.2)    |
//! | `topk_dt`           | `(data, vp, k, out_idx, len, largest)->i32`                        |
//!
//! where `dt` ∈ {f64, f32, i32, u32, u8}.
//!
//! ## Sort algorithm (argsort) — ABI v1.2
//!
//! Bottom-up stable merge sort using caller-provided scratch (ABI v1.2: the JS
//! dispatch layer allocates/frees an `i32[len]` scratch buffer around each call).
//!
//! * Initial runs: insertion sort in blocks of `INIT_RUN = 16`.
//! * Merge: copy the left half into `scratch[0..size_l]`, merge back into `perm`.
//!   `scratch` is always `len` elements, so the left half always fits — no rotation
//!   fallback, true O(n log n) for all input sizes and orderings.
//! * Both scalar and SIMD builds execute the same algorithm (comparisons are
//!   inherently sequential; no SIMD benefit for sorting).
//!
//! ## SIMD
//!
//! `filter_f64` SIMD build adds a bulk-copy fast path for all-ones mask bytes
//! (4 × f64x2 stores instead of 8 scalar stores). Behavioural output is identical
//! in both builds. All other kernels in this family are identical in both builds.

#[cfg(target_feature = "simd128")]
use core::arch::wasm32;

// ── Bitmap helpers ────────────────────────────────────────────────────────────

/// Read one bit from an Arrow-LSB bitmap; `i` is the element index.
#[inline(always)]
unsafe fn bit_get(bitmap: *const u8, i: usize) -> bool {
    (*bitmap.add(i >> 3) >> (i & 7)) & 1 != 0
}

/// Set one bit in an Arrow-LSB bitmap.
#[inline(always)]
unsafe fn bit_set_out(bitmap: *mut u8, i: usize) {
    *bitmap.add(i >> 3) |= 1u8 << (i & 7);
}

/// Return `true` if element `row` is valid. `vp == null` means all-valid (ABI §4.1).
#[inline(always)]
unsafe fn is_valid(vp: *const u8, row: usize) -> bool {
    vp.is_null() || bit_get(vp, row)
}

// ── filter_dt ─────────────────────────────────────────────────────────────────
//
// Compact data values where the Arrow-LSB mask bit = 1. Returns the output count.
// Padding bits in the last mask byte must be 0 (caller's responsibility per ABI §4.1).

/// Inner loop shared by scalar build and by the non-SIMD tail of the SIMD build.
#[inline]
unsafe fn filter_scalar<T: Copy>(
    data: *const T,
    mask: *const u8,
    out: *mut T,
    len: usize,
) -> usize {
    let full = len >> 3; // complete mask bytes
    let tail = len & 7; // remaining elements in last byte
    let mut count = 0usize;

    for b in 0..full {
        let base = b << 3;
        let mut m = *mask.add(b);
        while m != 0 {
            let bit = m.trailing_zeros() as usize;
            *out.add(count) = *data.add(base + bit);
            count += 1;
            m &= m - 1; // clear lowest set bit
        }
    }

    // Tail byte: only bits 0..tail are valid; mask off any padding.
    if tail > 0 {
        let base = full << 3;
        let mut m = *mask.add(full) & ((1u8 << tail) - 1);
        while m != 0 {
            let bit = m.trailing_zeros() as usize;
            *out.add(count) = *data.add(base + bit);
            count += 1;
            m &= m - 1;
        }
    }

    count
}

macro_rules! impl_filter {
    ($name:ident, $ty:ty) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(
            data_ptr: *const $ty,
            mask_ptr: *const u8,
            out_ptr: *mut $ty,
            len: u32,
        ) -> i32 {
            filter_scalar(data_ptr, mask_ptr, out_ptr, len as usize) as i32
        }
    };
}

impl_filter!(filter_f32, f32);
impl_filter!(filter_i32, i32);
impl_filter!(filter_u32, u32);
impl_filter!(filter_u8, u8);

// filter_f64: scalar build uses filter_scalar; SIMD build adds a bulk-copy
// fast path for all-ones mask bytes (4 × f64x2 SIMD stores).
#[no_mangle]
pub unsafe extern "C" fn filter_f64(
    data_ptr: *const f64,
    mask_ptr: *const u8,
    out_ptr: *mut f64,
    len: u32,
) -> i32 {
    let len = len as usize;
    filter_f64_impl(data_ptr, mask_ptr, out_ptr, len) as i32
}

#[cfg(target_feature = "simd128")]
unsafe fn filter_f64_impl(
    data_ptr: *const f64,
    mask_ptr: *const u8,
    out_ptr: *mut f64,
    len: usize,
) -> usize {
    let full = len >> 3;
    let tail = len & 7;
    let mut count = 0usize;

    for b in 0..full {
        let base = b << 3;
        let m_byte = *mask_ptr.add(b);

        if m_byte == 0xFF {
            // All 8 selected: bulk-copy using 4 × f64x2 SIMD stores.
            // data_ptr base is 16-byte aligned (ABI §3); each block of 8 f64s
            // starts at base*8 bytes which is a multiple of 64 → 16-byte aligned.
            let d0 = wasm32::v128_load(data_ptr.add(base) as *const wasm32::v128);
            let d1 = wasm32::v128_load(data_ptr.add(base + 2) as *const wasm32::v128);
            let d2 = wasm32::v128_load(data_ptr.add(base + 4) as *const wasm32::v128);
            let d3 = wasm32::v128_load(data_ptr.add(base + 6) as *const wasm32::v128);
            // Output may not be 16-byte aligned (count varies); WASM v128.store
            // works at any alignment (flat byte-addressed memory).
            wasm32::v128_store(out_ptr.add(count) as *mut wasm32::v128, d0);
            wasm32::v128_store(out_ptr.add(count + 2) as *mut wasm32::v128, d1);
            wasm32::v128_store(out_ptr.add(count + 4) as *mut wasm32::v128, d2);
            wasm32::v128_store(out_ptr.add(count + 6) as *mut wasm32::v128, d3);
            count += 8;
        } else if m_byte != 0 {
            let mut m = m_byte;
            while m != 0 {
                let bit = m.trailing_zeros() as usize;
                *out_ptr.add(count) = *data_ptr.add(base + bit);
                count += 1;
                m &= m - 1;
            }
        }
    }

    if tail > 0 {
        let base = full << 3;
        let mut m = *mask_ptr.add(full) & ((1u8 << tail) - 1);
        while m != 0 {
            let bit = m.trailing_zeros() as usize;
            *out_ptr.add(count) = *data_ptr.add(base + bit);
            count += 1;
            m &= m - 1;
        }
    }

    count
}

#[cfg(not(target_feature = "simd128"))]
unsafe fn filter_f64_impl(
    data_ptr: *const f64,
    mask_ptr: *const u8,
    out_ptr: *mut f64,
    len: usize,
) -> usize {
    filter_scalar(data_ptr, mask_ptr, out_ptr, len)
}

// ── filter_indices ────────────────────────────────────────────────────────────

#[no_mangle]
pub unsafe extern "C" fn filter_indices(
    mask_ptr: *const u8,
    out_idx: *mut i32,
    len: u32,
) -> i32 {
    let len = len as usize;
    let full = len >> 3;
    let tail = len & 7;
    let mut count = 0usize;

    for b in 0..full {
        let base = (b << 3) as i32;
        let mut m = *mask_ptr.add(b);
        while m != 0 {
            let bit = m.trailing_zeros() as i32;
            *out_idx.add(count) = base + bit;
            count += 1;
            m &= m - 1;
        }
    }

    if tail > 0 {
        let base = (full << 3) as i32;
        let mut m = *mask_ptr.add(full) & ((1u8 << tail) - 1);
        while m != 0 {
            let bit = m.trailing_zeros() as i32;
            *out_idx.add(count) = base + bit;
            count += 1;
            m &= m - 1;
        }
    }

    count as i32
}

// ── gather_dt ─────────────────────────────────────────────────────────────────
//
// `out[k] = data[idx[k]]` for k in 0..idx_len. idx_len may differ from the
// data array length (gather is a reindex / take operation).

macro_rules! impl_gather {
    ($name:ident, $ty:ty) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(
            data_ptr: *const $ty,
            idx_ptr: *const i32,
            idx_len: u32,
            out_ptr: *mut $ty,
        ) {
            let n = idx_len as usize;
            for k in 0..n {
                let row = *idx_ptr.add(k) as usize;
                *out_ptr.add(k) = *data_ptr.add(row);
            }
        }
    };
}

impl_gather!(gather_f64, f64);
impl_gather!(gather_f32, f32);
impl_gather!(gather_i32, i32);
impl_gather!(gather_u32, u32);
impl_gather!(gather_u8, u8);

// ── gather_validity ───────────────────────────────────────────────────────────
//
// Gather validity bits: out_vp bit k = vp bit idx[k].
// Output bitmap bytes are zeroed first (ensures padding bits = 0).

#[no_mangle]
pub unsafe extern "C" fn gather_validity(
    vp: *const u8,
    idx_ptr: *const i32,
    idx_len: u32,
    out_vp: *mut u8,
) {
    let n = idx_len as usize;
    if n == 0 {
        return;
    }

    // Zero the output bitmap (ceil(n/8) bytes).
    let out_bytes = (n + 7) >> 3;
    for i in 0..out_bytes {
        *out_vp.add(i) = 0;
    }

    for k in 0..n {
        let row = *idx_ptr.add(k) as usize;
        if bit_get(vp, row) {
            bit_set_out(out_vp, k);
        }
    }
}

// ── argsort: stable sort engine (ABI v1.2 — caller-provided scratch) ─────────
//
// Bottom-up merge sort using caller-provided `scratch` (`i32[len]`). The sort
// is stable: equal elements preserve their original relative order in `perm`.
//
// ABI v1.2 change: the old implementation fell back to O(n²) rotation-based
// in-place merge for left-halves > MERGE_BUF (1024). With a caller-provided
// scratch of exactly `len` elements the left half always fits, giving true
// O(n log n) for all input sizes and orderings.
//
// `cmp(a, b)` compares two perm VALUES (row indices). Returns `Less` if element
// `a` should come before element `b` in the sorted output.

const INIT_RUN: usize = 16;

/// Stable in-place sort of `perm[0..len]` keyed by `cmp`.
///
/// Uses bottom-up merge sort with caller-provided `scratch[0..len]` as merge
/// workspace. O(n log n) for all input sizes; no rotation fallback.
///
/// # Safety
/// `perm` and `scratch` must each point to at least `len` valid `i32` slots.
/// `scratch` may alias nothing that the caller still holds a reference to during
/// this call (it is write-only from the caller's perspective).
#[inline(never)]
unsafe fn stable_sort_perm_scratch<F>(perm: *mut i32, len: usize, scratch: *mut i32, cmp: F)
where
    F: Fn(i32, i32) -> core::cmp::Ordering,
{
    use core::cmp::Ordering::Less;

    if len <= 1 {
        return;
    }

    // ── Phase 1: insertion sort initial runs ─────────────────────────────────
    let mut run_lo = 0usize;
    while run_lo < len {
        let hi = (run_lo + INIT_RUN).min(len);
        let mut i = run_lo + 1;
        while i < hi {
            let key = *perm.add(i);
            let mut j = i;
            while j > run_lo && cmp(key, *perm.add(j - 1)) == Less {
                *perm.add(j) = *perm.add(j - 1);
                j -= 1;
            }
            *perm.add(j) = key;
            i += 1;
        }
        run_lo += INIT_RUN;
    }

    // ── Phase 2: bottom-up merge passes ──────────────────────────────────────
    // Copy the left half into scratch, then merge back into perm[lo..hi].
    // scratch is len elements — left half is ≤ width ≤ len/2, always fits.
    let mut width = INIT_RUN;
    while width < len {
        let mut lo = 0usize;
        while lo < len {
            let mid = (lo + width).min(len);
            let hi = (lo + 2 * width).min(len);
            if mid < hi {
                let size_l = mid - lo;
                // Copy left half into scratch.
                core::ptr::copy_nonoverlapping(perm.add(lo), scratch, size_l);
                let mut l = 0usize; // cursor into scratch (left half)
                let mut r = mid;    // cursor into perm (right half)
                let mut out = lo;   // write position in perm
                while l < size_l && r < hi {
                    let sl = *scratch.add(l);
                    let pr = *perm.add(r);
                    // Stable: prefer left (scratch) when equal.
                    if cmp(pr, sl) == Less {
                        *perm.add(out) = pr;
                        r += 1;
                    } else {
                        *perm.add(out) = sl;
                        l += 1;
                    }
                    out += 1;
                }
                // Flush remaining left elements (right tail is already in place).
                while l < size_l {
                    *perm.add(out) = *scratch.add(l);
                    l += 1;
                    out += 1;
                }
            }
            lo += 2 * width;
        }
        width *= 2;
    }
}

// ── argsort: per-dtype comparison functions ───────────────────────────────────
//
// Total order per dtypes.md §4.6:
//   ascending:  values (signed/unsigned/IEEE) | NaN | null   (null last)
//   descending: reversed values (NaN = largest, so first) | null (null still last)
//
// All NaN bit patterns compare equal (spec: "all NaN bit patterns compare equal").

#[inline(always)]
unsafe fn argsort_cmp_f64(
    data: *const f64,
    vp: *const u8,
    desc: bool,
    a: i32,
    b: i32,
) -> core::cmp::Ordering {
    use core::cmp::Ordering::{Equal, Greater, Less};
    let a_valid = is_valid(vp, a as usize);
    let b_valid = is_valid(vp, b as usize);
    // Nulls last in both directions.
    match (a_valid, b_valid) {
        (false, false) => return Equal,
        (false, true) => return Greater, // null > valid
        (true, false) => return Less,    // valid < null
        (true, true) => {}
    }
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();
    if desc {
        // Descending: NaN first (largest), then +inf downward; nulls still last.
        match (a_nan, b_nan) {
            (true, true) => Equal,   // all NaNs equal
            (true, false) => Less,   // NaN < non-NaN in desc order (NaN is "largest" → first)
            (false, true) => Greater,
            (false, false) => bv.partial_cmp(&av).unwrap_or(Equal), // reversed IEEE
        }
    } else {
        // Ascending: NaN after +inf.
        match (a_nan, b_nan) {
            (true, true) => Equal,
            (true, false) => Greater, // NaN after non-NaN
            (false, true) => Less,
            (false, false) => av.partial_cmp(&bv).unwrap_or(Equal),
        }
    }
}

#[inline(always)]
unsafe fn argsort_cmp_f32(
    data: *const f32,
    vp: *const u8,
    desc: bool,
    a: i32,
    b: i32,
) -> core::cmp::Ordering {
    use core::cmp::Ordering::{Equal, Greater, Less};
    let a_valid = is_valid(vp, a as usize);
    let b_valid = is_valid(vp, b as usize);
    match (a_valid, b_valid) {
        (false, false) => return Equal,
        (false, true) => return Greater,
        (true, false) => return Less,
        (true, true) => {}
    }
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();
    if desc {
        match (a_nan, b_nan) {
            (true, true) => Equal,
            (true, false) => Less,
            (false, true) => Greater,
            (false, false) => bv.partial_cmp(&av).unwrap_or(Equal),
        }
    } else {
        match (a_nan, b_nan) {
            (true, true) => Equal,
            (true, false) => Greater,
            (false, true) => Less,
            (false, false) => av.partial_cmp(&bv).unwrap_or(Equal),
        }
    }
}

#[inline(always)]
unsafe fn argsort_cmp_i32(
    data: *const i32,
    vp: *const u8,
    desc: bool,
    a: i32,
    b: i32,
) -> core::cmp::Ordering {
    use core::cmp::Ordering::{Equal, Greater, Less};
    let a_valid = is_valid(vp, a as usize);
    let b_valid = is_valid(vp, b as usize);
    match (a_valid, b_valid) {
        (false, false) => return Equal,
        (false, true) => return Greater,
        (true, false) => return Less,
        (true, true) => {}
    }
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if desc {
        bv.cmp(&av)
    } else {
        av.cmp(&bv)
    }
}

#[inline(always)]
unsafe fn argsort_cmp_u32(
    data: *const u32,
    vp: *const u8,
    desc: bool,
    a: i32,
    b: i32,
) -> core::cmp::Ordering {
    use core::cmp::Ordering::{Equal, Greater, Less};
    let a_valid = is_valid(vp, a as usize);
    let b_valid = is_valid(vp, b as usize);
    match (a_valid, b_valid) {
        (false, false) => return Equal,
        (false, true) => return Greater,
        (true, false) => return Less,
        (true, true) => {}
    }
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if desc {
        bv.cmp(&av)
    } else {
        av.cmp(&bv)
    }
}

// ── argsort exports (ABI v1.2) ────────────────────────────────────────────────

/// Stable sort of `inout_perm[0..len]` by `data[perm[i]]`.
///
/// `inout_perm` is caller-initialized (identity for single-key; previous sort
/// result for multi-key threading). `desc = 0` ascending, `1` descending.
/// Nulls sort last in both directions (dtypes.md §4.6). NaN sorts after +inf
/// ascending, first descending (as the "largest" value).
///
/// `scratch_ptr` (ABI v1.2): caller-allocated, 16-byte-aligned `i32[len]` merge
/// scratch. The JS dispatch layer (`src/kernels/select/index.ts`) allocates and
/// frees it around this call so the kernel itself never allocates.
#[no_mangle]
pub unsafe extern "C" fn argsort_f64(
    data_ptr: *const f64,
    vp: *const u8,
    inout_perm: *mut i32,
    len: u32,
    desc: i32,
    scratch_ptr: *mut i32,
) {
    let n = len as usize;
    if n <= 1 {
        return;
    }
    let d = desc != 0;
    stable_sort_perm_scratch(inout_perm, n, scratch_ptr, |a, b| {
        argsort_cmp_f64(data_ptr, vp, d, a, b)
    });
}

#[no_mangle]
pub unsafe extern "C" fn argsort_f32(
    data_ptr: *const f32,
    vp: *const u8,
    inout_perm: *mut i32,
    len: u32,
    desc: i32,
    scratch_ptr: *mut i32,
) {
    let n = len as usize;
    if n <= 1 {
        return;
    }
    let d = desc != 0;
    stable_sort_perm_scratch(inout_perm, n, scratch_ptr, |a, b| {
        argsort_cmp_f32(data_ptr, vp, d, a, b)
    });
}

#[no_mangle]
pub unsafe extern "C" fn argsort_i32(
    data_ptr: *const i32,
    vp: *const u8,
    inout_perm: *mut i32,
    len: u32,
    desc: i32,
    scratch_ptr: *mut i32,
) {
    let n = len as usize;
    if n <= 1 {
        return;
    }
    let d = desc != 0;
    stable_sort_perm_scratch(inout_perm, n, scratch_ptr, |a, b| {
        argsort_cmp_i32(data_ptr, vp, d, a, b)
    });
}

#[no_mangle]
pub unsafe extern "C" fn argsort_u32(
    data_ptr: *const u32,
    vp: *const u8,
    inout_perm: *mut i32,
    len: u32,
    desc: i32,
    scratch_ptr: *mut i32,
) {
    let n = len as usize;
    if n <= 1 {
        return;
    }
    let d = desc != 0;
    stable_sort_perm_scratch(inout_perm, n, scratch_ptr, |a, b| {
        argsort_cmp_u32(data_ptr, vp, d, a, b)
    });
}

// ── topk: heap-based k-selection ─────────────────────────────────────────────
//
// Algorithm:
//   1. Collect the first min(k, non-null count) valid indices into out_idx (fill).
//   2. Heapify out_idx[0..filled] as a min-heap (for largest=1) or max-heap (for
//      largest=0), where "root = element that would be replaced first".
//   3. Scan remaining valid indices: if an index beats the root, replace and sift down.
//   4. Insertion-sort out_idx[0..filled] for the output order:
//      largest=1 → descending; largest=0 → ascending; ties: lower index first.
//   5. Return filled count.
//
// Null handling: null elements are skipped (not counted against k).
// NaN handling: NaN participates as the largest valid value (dtypes.md §4.6).
//
// Heap comparison (min-heap semantics: root = "worst to keep"):
//   For largest=1: worst = smallest value (or equal value with higher row index).
//   For largest=0: worst = largest value (or equal value with higher row index).
//
// Output comparison (for final sort):
//   For largest=1: descending by value, ties by ascending row index.
//   For largest=0: ascending by value, ties by ascending row index.

/// Heap `less_than` for f64 min-heap (returns true if `a` should be at root).
#[inline(always)]
unsafe fn topk_heap_lt_f64(a: i32, b: i32, data: *const f64, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();

    if largest {
        // Root = worst = smallest value; NaN is largest so NaN never at root.
        // a < b (in heap order) means a is worse: smaller value, or equal + higher idx.
        match (a_nan, b_nan) {
            (true, true) => a > b,    // both NaN: higher index is worse
            (true, false) => false,   // NaN > anything: not worse
            (false, true) => true,    // anything < NaN: worse
            (false, false) => {
                use core::cmp::Ordering::{Equal, Less};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Less => true,
                    Equal => a > b,
                    _ => false,
                }
            }
        }
    } else {
        // Root = worst = largest value; NaN is largest so NaN IS at root worst.
        // a < b (in heap order) means a is worse: larger value, or equal + higher idx.
        match (a_nan, b_nan) {
            (true, true) => a > b,
            (true, false) => true,  // NaN is larger/worse for k-smallest
            (false, true) => false,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Greater};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Greater => true,
                    Equal => a > b,
                    _ => false,
                }
            }
        }
    }
}

/// Heap `less_than` for f32 min-heap.
#[inline(always)]
unsafe fn topk_heap_lt_f32(a: i32, b: i32, data: *const f32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();
    if largest {
        match (a_nan, b_nan) {
            (true, true) => a > b,
            (true, false) => false,
            (false, true) => true,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Less};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Less => true,
                    Equal => a > b,
                    _ => false,
                }
            }
        }
    } else {
        match (a_nan, b_nan) {
            (true, true) => a > b,
            (true, false) => true,
            (false, true) => false,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Greater};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Greater => true,
                    Equal => a > b,
                    _ => false,
                }
            }
        }
    }
}

/// Heap `less_than` for i32 min-heap.
#[inline(always)]
unsafe fn topk_heap_lt_i32(a: i32, b: i32, data: *const i32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest {
        av < bv || (av == bv && a > b)
    } else {
        av > bv || (av == bv && a > b)
    }
}

/// Heap `less_than` for u32 min-heap.
#[inline(always)]
unsafe fn topk_heap_lt_u32(a: i32, b: i32, data: *const u32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest {
        av < bv || (av == bv && a > b)
    } else {
        av > bv || (av == bv && a > b)
    }
}

/// Sift down element at `pos` in the heap `out[0..count]` using `heap_lt`.
#[inline]
unsafe fn heap_sift_down<F>(out: *mut i32, count: usize, mut pos: usize, heap_lt: F)
where
    F: Fn(i32, i32) -> bool,
{
    loop {
        let left = 2 * pos + 1;
        if left >= count {
            break;
        }
        let right = left + 1;
        // Find the "smaller" (worst) child — that's the one closer to root.
        let mut sm = left;
        if right < count && heap_lt(*out.add(right), *out.add(left)) {
            sm = right;
        }
        // If current element is already ≤ the smallest child, heap is satisfied.
        if !heap_lt(*out.add(sm), *out.add(pos)) {
            break;
        }
        // Swap and continue.
        let tmp = *out.add(pos);
        *out.add(pos) = *out.add(sm);
        *out.add(sm) = tmp;
        pos = sm;
    }
}

/// Build a min-heap in-place over `out[0..count]`.
#[inline]
unsafe fn heap_build<F>(out: *mut i32, count: usize, heap_lt: F)
where
    F: Fn(i32, i32) -> bool + Copy,
{
    if count < 2 {
        return;
    }
    let mut i = count / 2;
    while i > 0 {
        i -= 1;
        heap_sift_down(out, count, i, heap_lt);
    }
}

/// Output comparison for final sort of the k results.
/// Returns true if a should come before b in the output.
#[inline(always)]
unsafe fn topk_output_lt_f64(a: i32, b: i32, data: *const f64, largest: bool) -> bool {
    // largest=1: descending (largest first); largest=0: ascending (smallest first).
    // Ties: lower row index first.
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();
    if largest {
        // Descending: NaN first (largest), then values desc. Ties: lower index first.
        match (a_nan, b_nan) {
            (true, true) => a < b,
            (true, false) => true,   // NaN before non-NaN in desc
            (false, true) => false,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Greater};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Greater => true,
                    Equal => a < b,
                    _ => false,
                }
            }
        }
    } else {
        // Ascending: values asc, NaN last. Ties: lower index first.
        match (a_nan, b_nan) {
            (true, true) => a < b,
            (true, false) => false,  // NaN after non-NaN in asc
            (false, true) => true,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Less};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Less => true,
                    Equal => a < b,
                    _ => false,
                }
            }
        }
    }
}

#[inline(always)]
unsafe fn topk_output_lt_f32(a: i32, b: i32, data: *const f32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    let a_nan = av.is_nan();
    let b_nan = bv.is_nan();
    if largest {
        match (a_nan, b_nan) {
            (true, true) => a < b,
            (true, false) => true,
            (false, true) => false,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Greater};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Greater => true,
                    Equal => a < b,
                    _ => false,
                }
            }
        }
    } else {
        match (a_nan, b_nan) {
            (true, true) => a < b,
            (true, false) => false,
            (false, true) => true,
            (false, false) => {
                use core::cmp::Ordering::{Equal, Less};
                match av.partial_cmp(&bv).unwrap_or(Equal) {
                    Less => true,
                    Equal => a < b,
                    _ => false,
                }
            }
        }
    }
}

#[inline(always)]
unsafe fn topk_output_lt_i32(a: i32, b: i32, data: *const i32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest {
        av > bv || (av == bv && a < b)
    } else {
        av < bv || (av == bv && a < b)
    }
}

#[inline(always)]
unsafe fn topk_output_lt_u32(a: i32, b: i32, data: *const u32, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest {
        av > bv || (av == bv && a < b)
    } else {
        av < bv || (av == bv && a < b)
    }
}

/// Insertion sort `out[0..count]` for the final output. k is small in practice.
#[inline]
unsafe fn topk_insertion_sort<F>(out: *mut i32, count: usize, lt: F)
where
    F: Fn(i32, i32) -> bool,
{
    let mut i = 1usize;
    while i < count {
        let key = *out.add(i);
        let mut j = i;
        while j > 0 && lt(key, *out.add(j - 1)) {
            *out.add(j) = *out.add(j - 1);
            j -= 1;
        }
        *out.add(j) = key;
        i += 1;
    }
}

macro_rules! impl_topk {
    (
        $name:ident, $ty:ty,
        $heap_lt:ident,
        $output_lt:ident
    ) => {
        #[no_mangle]
        pub unsafe extern "C" fn $name(
            data_ptr: *const $ty,
            vp: *const u8,
            k: i32,
            out_idx: *mut i32,
            len: u32,
            largest: i32,
        ) -> i32 {
            let k = k as usize;
            let len = len as usize;
            let largest = largest != 0;

            if k == 0 || len == 0 {
                return 0;
            }

            let mut filled = 0usize; // elements currently in the heap

            for i in 0..len {
                if !is_valid(vp, i) {
                    continue; // skip null rows
                }
                let idx = i as i32;

                if filled < k {
                    // Fill phase: accumulate first k valid indices.
                    *out_idx.add(filled) = idx;
                    filled += 1;
                    // Once we have exactly k elements, build the heap.
                    if filled == k {
                        heap_build(out_idx, filled, |a, b| $heap_lt(a, b, data_ptr, largest));
                    }
                } else {
                    // Replacement phase: compare with root.
                    let root = *out_idx; // root is at index 0
                    if $heap_lt(root, idx, data_ptr, largest) {
                        // root is "worse" than new candidate → replace root.
                        *out_idx = idx;
                        heap_sift_down(out_idx, filled, 0, |a, b| {
                            $heap_lt(a, b, data_ptr, largest)
                        });
                    }
                }
            }

            // Sort the collected indices for the required output order.
            topk_insertion_sort(out_idx, filled, |a, b| $output_lt(a, b, data_ptr, largest));

            filled as i32
        }
    };
}

impl_topk!(topk_f64, f64, topk_heap_lt_f64, topk_output_lt_f64);
impl_topk!(topk_f32, f32, topk_heap_lt_f32, topk_output_lt_f32);
impl_topk!(topk_i32, i32, topk_heap_lt_i32, topk_output_lt_i32);
impl_topk!(topk_u32, u32, topk_heap_lt_u32, topk_output_lt_u32);

// ========================================================================
// § i64 select kernels (v2.3) — wasm-abi.md §10
// ========================================================================

impl_filter!(filter_i64, i64);
impl_gather!(gather_i64, i64);

#[inline(always)]
unsafe fn argsort_cmp_i64(
    data: *const i64,
    vp: *const u8,
    desc: bool,
    a: i32,
    b: i32,
) -> core::cmp::Ordering {
    use core::cmp::Ordering::{Equal, Greater, Less};
    let a_valid = is_valid(vp, a as usize);
    let b_valid = is_valid(vp, b as usize);
    match (a_valid, b_valid) {
        (false, false) => return Equal,
        (false, true)  => return Greater,
        (true,  false) => return Less,
        (true,  true)  => {}
    }
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if desc { bv.cmp(&av) } else { av.cmp(&bv) }
}

#[no_mangle]
pub unsafe extern "C" fn argsort_i64(
    data_ptr: *const i64,
    vp: *const u8,
    inout_perm: *mut i32,
    len: u32,
    desc: i32,
    scratch_ptr: *mut i32,
) {
    let n = len as usize;
    if n <= 1 { return; }
    let d = desc != 0;
    stable_sort_perm_scratch(inout_perm, n, scratch_ptr, |a, b| {
        argsort_cmp_i64(data_ptr, vp, d, a, b)
    });
}

#[inline(always)]
unsafe fn topk_heap_lt_i64(a: i32, b: i32, data: *const i64, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest { av < bv || (av == bv && a > b) }
    else       { av > bv || (av == bv && a > b) }
}

#[inline(always)]
unsafe fn topk_output_lt_i64(a: i32, b: i32, data: *const i64, largest: bool) -> bool {
    let av = *data.add(a as usize);
    let bv = *data.add(b as usize);
    if largest { av > bv || (av == bv && a < b) }
    else       { av < bv || (av == bv && a < b) }
}

impl_topk!(topk_i64, i64, topk_heap_lt_i64, topk_output_lt_i64);
