#!/usr/bin/env node
/**
 * Extract every ```typescript block from README.md and type-check them against
 * the built dist/index.d.ts.  Run after `npm run build`.
 *
 * Usage:
 *   node scripts/check-readme.mjs
 *   npm run check:readme
 *
 * How it works:
 *   1. Extracts all ```typescript ... ``` blocks from README.md.
 *   2. Strips import lines, merges them by module (deduplicates re-exports of
 *      the same name across blocks), and wraps each block in its own async IIFE
 *      so variable names don't clash.
 *   3. Emits a single .ts file + a temporary tsconfig that maps 'databonk' →
 *      dist/index.d.ts and 'databonk/workers' → dist/workers.d.ts.
 *   4. Runs tsc --noEmit and exits 1 on type errors.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, '..');
const README = join(ROOT, 'README.md');
const CACHE = join(ROOT, 'node_modules', '.cache', 'check-readme');

mkdirSync(CACHE, { recursive: true });

// ── 1. Extract ```typescript blocks ──────────────────────────────────────────

const src = readFileSync(README, 'utf8');
const snippets = [];
const re = /```typescript\n([\s\S]*?)```/g;
let m;
while ((m = re.exec(src)) !== null) {
  snippets.push(m[1]);
}

if (snippets.length === 0) {
  console.error('check-readme: no TypeScript snippets found in README.md');
  process.exit(1);
}

console.log(`check-readme: found ${snippets.length} TypeScript snippet(s) in README.md`);

// ── 2. Collect imports (merged per module) and build per-block IIFEs ─────────
//
// Multiple snippets may import the same name from 'databonk'.  Collecting them all
// as-is produces duplicate identifiers.  We parse named imports per module and
// emit a single merged import per module.
//
// Note on the lambda escape-hatch block: `df.filterFn(r => r.value > 5)` is
// deliberately dynamically-typed — Row is Record<string,Cell> and TypeScript
// cannot verify cross-type comparisons.  We add // @ts-ignore before those
// lines in the GENERATED file only; the README itself is unchanged.

/** @type {Map<string, Set<string>>} */
const importsByModule = new Map();

const cleanedBlocks = snippets.map((s, i) => {
  const lines = s.split('\n').filter((line) => {
    if (!line.startsWith('import ')) return true;
    // Parse:  import { A, B as C } from 'module';
    const imp = line.match(/^import\s*\{([^}]+)\}\s*from\s*['"]([^'"]+)['"]/);
    if (imp) {
      const mod = imp[2];
      if (!importsByModule.has(mod)) importsByModule.set(mod, new Set());
      const ns = importsByModule.get(mod);
      for (const raw of imp[1].split(',')) {
        const clean = raw.trim().replace(/\s+as\s+\S+/, '');
        if (clean) ns.add(clean);
      }
    }
    return false; // strip from snippet body
  });

  // Add // @ts-ignore before filterFn / mapFn calls: Row = Record<string,Cell>
  // and TypeScript flags Cell comparisons (e.g. r.value > 5) even though the
  // pattern is intentionally dynamic (README's "slow path" escape hatch).
  const patched = lines.map((line) => {
    if (/\.(filterFn|mapFn)\(/.test(line)) {
      return `// @ts-ignore — Row is Record<string,Cell>; dynamic comparisons are intentional\n${line}`;
    }
    return line;
  });

  return `/* === README snippet ${i} === */\nvoid (async () => {\n${patched.join('\n')}\n})();`;
});

// ── 3. Build the combined .ts file ───────────────────────────────────────────

const mergedImports = [...importsByModule.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([mod, names]) => `import { ${[...names].sort().join(', ')} } from '${mod}';`);

const header = [
  '// Auto-generated by scripts/check-readme.mjs — DO NOT EDIT',
  ...mergedImports,
  '',
  '// Stubs for variables referenced across snippets without being declared in that snippet',
  'declare const csvText: string;',
  'declare const df: import("databonk").DataFrame;',
  'declare const dataPtr: number;',
  'declare const vpPtr: number;',
  'declare const len: number;',
  'declare const bytes: Uint8Array;',
].join('\n');

const fileContent = [header, '', ...cleanedBlocks, ''].join('\n');

const tsFile = join(CACHE, 'readme-snippets.ts');
writeFileSync(tsFile, fileContent);

// ── 4. Emit a temporary tsconfig ─────────────────────────────────────────────
//
// moduleResolution: bundler + paths lets us resolve 'databonk' → dist/index.d.ts
// without installing the package as an npm dep.  baseUrl is the project root so
// the paths are relative to it.

const tsconfig = {
  compilerOptions: {
    target: 'ES2022',
    module: 'ES2022',
    moduleResolution: 'bundler',
    lib: ['ES2022', 'DOM'],
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    esModuleInterop: true,
    baseUrl: ROOT,
    paths: {
      databonk: ['dist/index.d.ts'],
      'databonk/workers': ['dist/workers.d.ts'],
      'databonk/parquet': ['dist/parquet.d.ts'],
    },
  },
  files: [tsFile],
};

const tsconfigFile = join(CACHE, 'tsconfig.json');
writeFileSync(tsconfigFile, JSON.stringify(tsconfig, null, 2));

// ── 5. Run tsc ────────────────────────────────────────────────────────────────

try {
  execSync(`npx tsc --project ${tsconfigFile}`, {
    cwd: ROOT,
    stdio: 'inherit',
  });
  console.log(`\ncheck-readme: PASSED — all ${snippets.length} README TypeScript snippets type-check OK\n`);
  process.exit(0);
} catch {
  console.error(`\ncheck-readme: FAILED — fix the TypeScript errors above\n`);
  process.exit(1);
}
